import LanglandsFirstMainLemma.Ramification.Different
import LanglandsFirstMainLemma.Ramification.LowerGroups
import LanglandsFirstMainLemma.Ramification.NormFiltration
import LanglandsFirstMainLemma.Ramification.SymmetricBounds
import LanglandsSecondMainLemma.Dyadic.Maximal.Alignment
import LanglandsSecondMainLemma.Algebra.BiquadraticE2

/-!
# Dyadic / Maximal / Origin

This file formalizes the aligned Kummer origin in the maximal mixed-dyadic
case.  Starting with the actual aligned generators supplied by `Alignment`,
it uses the three genuine quadratic intermediate fields and their
nontrivial automorphisms to compute the complete norm--trace table
`D:MX:origin-table`.  It also proves every order assertion in
`D:MX:valuations`, including the lower bounds on both error terms.

Blueprint: `blueprint/tasks/Dyadic/Maximal/Origin.md`.
Paper: lines 6820--6851 and 6934--6972 of `references/epsilon_SML.tex`.
-/

namespace LanglandsSecondMainLemma.Dyadic.Maximal

open LanglandsFirstMainLemma

noncomputable section

private theorem natCast_withTop_eq_intCast (n : ℕ) :
    (n : WithTop ℤ) = ((n : ℤ) : WithTop ℤ) := by
  norm_num

namespace AlignmentData

variable {F K : Type*} [Field F] [ValuativeRel F] [TopologicalSpace F]
  [IsNonarchimedeanLocalField F] [Field K] [Algebra F K]
variable {pi : ringOfIntegers F} {e a b : ℕ}
  {u0 w0 : (ringOfIntegers F)ˣ} {s R0 : K}

/-- The paper's first quadratic field, generated by the aligned `S`. -/
def firstField (D : AlignmentData pi e a b u0 w0 s R0) :
    IntermediateField F K :=
  IntermediateField.adjoin F {D.S}

/-- The paper's second quadratic field, generated by the aligned `R`. -/
def secondField (D : AlignmentData pi e a b u0 w0 s R0) :
    IntermediateField F K :=
  IntermediateField.adjoin F {D.R}

/-- The paper's third quadratic field, generated by `S * R`. -/
def thirdField (D : AlignmentData pi e a b u0 w0 s R0) :
    IntermediateField F K :=
  IntermediateField.adjoin F {D.S * D.R}

/-- `S`, regarded as an element of the first intermediate field. -/
def firstGenerator (D : AlignmentData pi e a b u0 w0 s R0) : D.firstField :=
  ⟨D.S, IntermediateField.mem_adjoin_simple_self F D.S⟩

/-- `R`, regarded as an element of the second intermediate field. -/
def secondGenerator (D : AlignmentData pi e a b u0 w0 s R0) : D.secondField :=
  ⟨D.R, IntermediateField.mem_adjoin_simple_self F D.R⟩

/-- `S * R`, regarded as an element of the third intermediate field. -/
def thirdGenerator (D : AlignmentData pi e a b u0 w0 s R0) : D.thirdField :=
  ⟨D.S * D.R, IntermediateField.mem_adjoin_simple_self F (D.S * D.R)⟩

/-- The aligned origin `Y = (S + R - 1) / 2`. -/
def origin (D : AlignmentData pi e a b u0 w0 s R0) : K :=
  (D.S + D.R - 1) / 2

/-- The difference error `B₀ = (epsilon - R²) / 4`. -/
def B0 (D : AlignmentData pi e a b u0 w0 s R0) : F :=
  (D.epsilon - D.rSquare) / 4

/-- The sum error `C₀ = (epsilon + R²) / 4`. -/
def C0 (D : AlignmentData pi e a b u0 w0 s R0) : F :=
  (D.epsilon + D.rSquare) / 4

/-- The first upper norm `a₁`. -/
def a1 (D : AlignmentData pi e a b u0 w0 s R0) : D.firstField :=
  norm D.firstField K D.origin

/-- The second upper norm `a₂`. -/
def a2 (D : AlignmentData pi e a b u0 w0 s R0) : D.secondField :=
  norm D.secondField K D.origin

/-- The third upper norm `a₃`. -/
def a3 (D : AlignmentData pi e a b u0 w0 s R0) : D.thirdField :=
  norm D.thirdField K D.origin

/-- The first upper trace `h₁`. -/
def h1 (D : AlignmentData pi e a b u0 w0 s R0) : D.firstField :=
  trace D.firstField K D.origin

/-- The second upper trace `h₂`. -/
def h2 (D : AlignmentData pi e a b u0 w0 s R0) : D.secondField :=
  trace D.secondField K D.origin

/-- The third upper trace `h₃`. -/
def h3 (D : AlignmentData pi e a b u0 w0 s R0) : D.thirdField :=
  trace D.thirdField K D.origin

/-- The first lower coefficient `beta₁ = N_{L₁/F}(h₁)`. -/
def beta1 (D : AlignmentData pi e a b u0 w0 s R0) : F :=
  norm F D.firstField D.h1

/-- The second lower coefficient `beta₂ = N_{L₂/F}(h₂)`. -/
def beta2 (D : AlignmentData pi e a b u0 w0 s R0) : F :=
  norm F D.secondField D.h2

/-- The third lower coefficient `beta₃ = N_{L₃/F}(h₃)`. -/
def beta3 (D : AlignmentData pi e a b u0 w0 s R0) : F :=
  norm F D.thirdField D.h3

end AlignmentData

/-- The intrinsic normalized order on an actual intermediate field, using
the accepted restriction of the top local-field valuation. -/
def intermediateOrder
    {F K : Type*} [Field F] [ValuativeRel F] [TopologicalSpace F]
    [IsNonarchimedeanLocalField F]
    [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K]
    [Algebra F K] [ValuativeExtension F K] [Module.Finite F K]
    (L : IntermediateField F K) (x : L) : WithTop ℤ := by
  letI : ValuativeRel L := Basic.intermediateFieldValuativeRel L
  letI : TopologicalSpace L := Basic.intermediateFieldTopology L
  letI : IsNonarchimedeanLocalField L := Basic.intermediateField_localField L
  exact ord L x

/-- Trace through a quadratic Galois edge, evaluated using its chosen
nonidentity automorphism. -/
private theorem quadratic_trace_eq
    {E M : Type*} [Field E] [Field M] [Algebra E M]
    [FiniteDimensional E M] [IsGalois E M]
    (sigma : Gal(M/E)) (hsigma : sigma ≠ 1)
    (hdegree : Module.finrank E M = 2) (x : M) :
    algebraMap E M (trace E M x) = x + sigma x := by
  classical
  rw [trace_eq_sum_automorphisms]
  have hcard : Fintype.card Gal(M/E) = 2 := by
    rw [Fintype.card_eq_nat_card, IsGalois.card_aut_eq_finrank, hdegree]
  have huniv : ({sigma, (1 : Gal(M/E))} : Finset Gal(M/E)) = Finset.univ := by
    apply Finset.eq_univ_of_card
    rw [Finset.card_insert_of_notMem (by simpa using hsigma),
      Finset.card_singleton, hcard]
  rw [← huniv]
  simp [hsigma, add_comm]

/-- Norm through a quadratic Galois edge, evaluated using its chosen
nonidentity automorphism. -/
private theorem quadratic_norm_eq
    {E M : Type*} [Field E] [Field M] [Algebra E M]
    [FiniteDimensional E M] [IsGalois E M]
    (sigma : Gal(M/E)) (hsigma : sigma ≠ 1)
    (hdegree : Module.finrank E M = 2) (x : M) :
    algebraMap E M (norm E M x) = x * sigma x := by
  classical
  rw [Algebra.norm_eq_prod_automorphisms]
  have hcard : Fintype.card Gal(M/E) = 2 := by
    rw [Fintype.card_eq_nat_card, IsGalois.card_aut_eq_finrank, hdegree]
  have huniv : ({sigma, (1 : Gal(M/E))} : Finset Gal(M/E)) = Finset.univ := by
    apply Finset.eq_univ_of_card
    rw [Finset.card_insert_of_notMem (by simpa using hsigma),
      Finset.card_singleton, hcard]
  rw [← huniv]
  simp [hsigma, mul_comm]

/-- Residue degrees multiply through the accepted valuation-compatible
structure on an actual intermediate field. -/
private theorem intermediate_residueDegree_mul
    {F K : Type*} [Field F] [ValuativeRel F] [TopologicalSpace F]
    [IsNonarchimedeanLocalField F]
    [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K]
    [Algebra F K] [ValuativeExtension F K] [Module.Finite F K]
    (L : IntermediateField F K) :
    letI : ValuativeRel L := Basic.intermediateFieldValuativeRel L
    letI : TopologicalSpace L := Basic.intermediateFieldTopology L
    letI : IsNonarchimedeanLocalField L := Basic.intermediateField_localField L
    letI : ValuativeExtension F L :=
      Basic.intermediateField_lowerValuativeExtension L
    letI : ValuativeExtension L K :=
      Basic.intermediateField_upperValuativeExtension L
    residueDegree F L * residueDegree L K = residueDegree F K := by
  letI : ValuativeRel L := Basic.intermediateFieldValuativeRel L
  letI : TopologicalSpace L := Basic.intermediateFieldTopology L
  letI : IsNonarchimedeanLocalField L := Basic.intermediateField_localField L
  letI : ValuativeExtension F L :=
    Basic.intermediateField_lowerValuativeExtension L
  letI : ValuativeExtension L K :=
    Basic.intermediateField_upperValuativeExtension L
  letI : IsScalarTower
      (ringOfIntegers F) (ringOfIntegers L) (ringOfIntegers K) :=
    IsScalarTower.of_algebraMap_eq' (by
      ext x
      change algebraMap F K (x : F) = algebraMap L K (algebraMap F L (x : F))
      rw [← IsScalarTower.algebraMap_apply F L K])
  letI : IsLocalHom
      (algebraMap (ringOfIntegers F) (ringOfIntegers L)) := inferInstance
  letI : IsLocalHom
      (algebraMap (ringOfIntegers L) (ringOfIntegers K)) := inferInstance
  rw [residueDegree_eq_finrank_residueField,
    residueDegree_eq_finrank_residueField,
    residueDegree_eq_finrank_residueField]
  exact Module.finrank_mul_finrank
    (ResidueField F) (ResidueField L) (ResidueField K)

/-- If `x² = 1 + epsilon`, with the odd square defect of the maximal
dyadic case, then both conjugate factors `x-1` and `x+1` have order `b`.
Only the first equality is needed below. -/
private theorem sqrt_one_sub_order
    {E M : Type*} [Field E] [ValuativeRel E] [TopologicalSpace E]
    [IsNonarchimedeanLocalField E]
    [Field M] [ValuativeRel M] [TopologicalSpace M]
    [IsNonarchimedeanLocalField M]
    [Algebra E M] [ValuativeExtension E M]
    (e a b : ℕ) (htwo : ord E (2 : E) = (e : WithTop ℤ))
    (ha : 1 ≤ a) (hae : a ≤ e) (hb : b = 2 * e - 2 * a + 1)
    (epsilon : E) (hepsilon : ord E epsilon = (b : WithTop ℤ))
    (hram : ramificationIndex E M = 2) (x : M)
    (hx : x ^ 2 = algebraMap E M (1 + epsilon)) :
    ord M (x - 1) = (b : WithTop ℤ) := by
  have hbpos : 0 < b := by omega
  have hblt : b < 2 * e := by omega
  have hepsilon0 : epsilon ≠ 0 :=
    (ord_ne_top_iff E).1 (by rw [hepsilon]; exact WithTop.coe_ne_top)
  have hprod : (x - 1) * (x + 1) = algebraMap E M epsilon := by
    calc
      (x - 1) * (x + 1) = x ^ 2 - 1 := by ring
      _ = algebraMap E M (1 + epsilon) - 1 := by rw [hx]
      _ = algebraMap E M epsilon := by simp
  have hminus0 : x - 1 ≠ 0 := by
    intro h
    have : algebraMap E M epsilon = 0 := by rw [← hprod, h, zero_mul]
    exact hepsilon0 ((algebraMap E M).injective (by simpa using this))
  have hplus0 : x + 1 ≠ 0 := by
    intro h
    have : algebraMap E M epsilon = 0 := by rw [← hprod, h, mul_zero]
    exact hepsilon0 ((algebraMap E M).injective (by simpa using this))
  obtain ⟨m, hm⟩ := WithTop.ne_top_iff_exists.mp
    ((ord_ne_top_iff M).2 hminus0)
  obtain ⟨n, hn⟩ := WithTop.ne_top_iff_exists.mp
    ((ord_ne_top_iff M).2 hplus0)
  have hsum : m + n = 2 * (b : ℤ) := by
    have h := congrArg (ord M) hprod
    rw [ord_mul, ord_algebraMap, hram, hepsilon] at h
    have hcast : ((m + n : ℤ) : WithTop ℤ) =
        ((2 * (b : ℤ) : ℤ) : WithTop ℤ) := by
      rw [WithTop.coe_add, hm, hn]
      rw [natCast_withTop_eq_intCast b] at h
      rw [← WithTop.coe_nsmul] at h
      norm_num [nsmul_eq_mul] at h ⊢
      exact h
    exact WithTop.coe_eq_coe.mp hcast
  have hmn : m = n := by
    by_contra hne
    have hordDiff : ord M ((x + 1) - (x - 1)) =
        min (ord M (x + 1)) (ord M (x - 1)) := by
      have horders : ord M (x + 1) ≠ ord M (-(x - 1)) := by
        intro heq
        apply hne
        apply WithTop.coe_eq_coe.mp
        calc
          (m : WithTop ℤ) = ord M (x - 1) := hm
          _ = ord M (-(x - 1)) := (ord_neg M (x - 1)).symm
          _ = ord M (x + 1) := heq.symm
          _ = (n : WithTop ℤ) := hn.symm
      rw [sub_eq_add_neg, ord_add_eq_min M horders, ord_neg]
    have htwoM : ord M (algebraMap E M (2 : E)) =
        ((2 * e : ℕ) : WithTop ℤ) := by
      rw [ord_algebraMap, hram, htwo,
        natCast_withTop_eq_intCast e,
        natCast_withTop_eq_intCast (2 * e), ← WithTop.coe_nsmul]
      simp only [nsmul_eq_mul]
      congr 1
    have hmin : min n m = 2 * (e : ℤ) := by
      have h := hordDiff
      rw [show (x + 1) - (x - 1) = algebraMap E M (2 : E) by
        simp only [map_ofNat]
        ring, htwoM, ← hn, ← hm] at h
      rw [natCast_withTop_eq_intCast (2 * e)] at h
      exact WithTop.coe_eq_coe.mp h.symm
    have hmge : 2 * (e : ℤ) ≤ m := by omega
    have hnge : 2 * (e : ℤ) ≤ n := by omega
    have : 4 * (e : ℤ) ≤ m + n := by omega
    omega
  have hmval : m = b := by omega
  rw [← hm]
  exact_mod_cast hmval

/-- A square root of a base element of odd order `b` has order `b` in a
ramified quadratic extension. -/
private theorem square_root_order
    {E M : Type*} [Field E] [ValuativeRel E] [TopologicalSpace E]
    [IsNonarchimedeanLocalField E]
    [Field M] [ValuativeRel M] [TopologicalSpace M]
    [IsNonarchimedeanLocalField M]
    [Algebra E M] [ValuativeExtension E M]
    (b : ℕ) (c : E) (hc : ord E c = (b : WithTop ℤ))
    (hram : ramificationIndex E M = 2) (x : M)
    (hx : x ^ 2 = algebraMap E M c) :
    ord M x = (b : WithTop ℤ) := by
  have hc0 : c ≠ 0 :=
    (ord_ne_top_iff E).1 (by rw [hc]; exact WithTop.coe_ne_top)
  have hx0 : x ≠ 0 := by
    intro h
    have : algebraMap E M c = 0 := by rw [← hx, h, zero_pow (by norm_num)]
    exact hc0 ((algebraMap E M).injective (by simpa using this))
  obtain ⟨z, hz⟩ := WithTop.ne_top_iff_exists.mp
    ((ord_ne_top_iff M).2 hx0)
  have h := congrArg (ord M) hx
  rw [ord_pow, ord_algebraMap, hram, hc] at h
  rw [← hz] at h
  rw [natCast_withTop_eq_intCast b] at h
  norm_num [nsmul_eq_mul] at h
  have hzEq : 2 * z = 2 * (b : ℤ) := by
    change (((2 : ℤ) * z : ℤ) : WithTop ℤ) =
      (((2 * b : ℕ) : ℕ) : WithTop ℤ) at h
    have h' := WithTop.coe_eq_coe.mp h
    norm_num at h' ⊢
    exact h'
  have : z = b := by omega
  rw [← hz]
  exact_mod_cast this

/-- Dividing an element of order `b = 2e - 2a + 1` by two in a ramified
quadratic extension gives the paper's order `1 - 2a`. -/
private theorem div_two_order
    {E M : Type*} [Field E] [ValuativeRel E] [TopologicalSpace E]
    [IsNonarchimedeanLocalField E]
    [Field M] [ValuativeRel M] [TopologicalSpace M]
    [IsNonarchimedeanLocalField M]
    [Algebra E M] [ValuativeExtension E M]
    (e a b : ℕ) (htwo : ord E (2 : E) = (e : WithTop ℤ))
    (hae : a ≤ e) (hb : b = 2 * e - 2 * a + 1)
    (hram : ramificationIndex E M = 2) (x : M)
    (hx : ord M x = (b : WithTop ℤ)) :
    ord M (x / 2) = (((1 : ℤ) - 2 * a : ℤ) : WithTop ℤ) := by
  have htwoM : ord M (2 : M) = (((2 * e : ℕ) : ℤ) : WithTop ℤ) := by
    rw [← map_ofNat (algebraMap E M) 2, ord_algebraMap, hram, htwo,
      natCast_withTop_eq_intCast e, ← WithTop.coe_nsmul]
    simp only [nsmul_eq_mul]
    congr 1
  rw [ord_div, hx, htwoM, natCast_withTop_eq_intCast b]
  change ((((b : ℤ) - (2 * e : ℕ) : ℤ)) : WithTop ℤ) = _
  congr 1
  push_cast [hb, Nat.cast_sub (Nat.mul_le_mul_left 2 hae)]
  omega

variable {F K : Type*} [Field F] [ValuativeRel F] [TopologicalSpace F]
  [IsNonarchimedeanLocalField F]
  [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K]
  [Algebra F K] [ValuativeExtension F K]
  [Module.Free F K] [Module.Finite F K] [IsGalois F K]
variable {pi : ringOfIntegers F} {e a b : ℕ}
  {u0 w0 : (ringOfIntegers F)ˣ} {s R0 : K}

/-- The complete exact table and valuation ledger attached to the aligned
origin.  The fields are the literal intermediate fields generated by
`S`, `R`, and `S*R`; the norm and trace entries are Mathlib/FML's actual
field norm and trace. -/
structure OriginData (D : AlignmentData pi e a b u0 w0 s R0) : Prop where
  first_degree : Module.finrank F D.firstField = 2
  second_degree : Module.finrank F D.secondField = 2
  third_degree : Module.finrank F D.thirdField = 2
  B0_order : (((1 : ℤ) - a : ℤ) : WithTop ℤ) ≤ ord F D.B0
  C0_order : (((1 : ℤ) - a : ℤ) : WithTop ℤ) ≤ ord F D.C0
  a1_table : algebraMap D.firstField K D.a1 =
    (1 - D.S) / 2 + algebraMap F K D.B0
  h1_table : algebraMap D.firstField K D.h1 = D.S - 1
  beta1_table : D.beta1 = -D.epsilon
  a2_table : algebraMap D.secondField K D.a2 =
    -D.R / 2 - algebraMap F K D.B0
  h2_table : algebraMap D.secondField K D.h2 = D.R - 1
  beta2_table : D.beta2 = 1 - D.rSquare
  a3_table : algebraMap D.thirdField K D.a3 =
    -(D.S * D.R) / 2 - algebraMap F K D.C0
  h3_table : algebraMap D.thirdField K D.h3 = -1
  beta3_table : D.beta3 = 1
  origin_order : ord K D.origin =
    (((1 : ℤ) - 2 * a : ℤ) : WithTop ℤ)
  a1_order : intermediateOrder D.firstField D.a1 =
    (((1 : ℤ) - 2 * a : ℤ) : WithTop ℤ)
  a2_order : intermediateOrder D.secondField D.a2 =
    (((1 : ℤ) - 2 * a : ℤ) : WithTop ℤ)
  a3_order : intermediateOrder D.thirdField D.a3 =
    (((1 : ℤ) - 2 * a : ℤ) : WithTop ℤ)
  h1_order : intermediateOrder D.firstField D.h1 = (b : WithTop ℤ)
  h2_order : intermediateOrder D.secondField D.h2 = 0
  h3_order : intermediateOrder D.thirdField D.h3 = 0
  beta1_order : ord F D.beta1 = (b : WithTop ℤ)
  beta2_order : ord F D.beta2 = 0
  beta3_order : ord F D.beta3 = 0
  origin_ne_zero : D.origin ≠ 0
  a1_ne_zero : D.a1 ≠ 0
  a2_ne_zero : D.a2 ≠ 0
  a3_ne_zero : D.a3 ≠ 0
  h1_ne_zero : D.h1 ≠ 0
  h2_ne_zero : D.h2 ≠ 0
  h3_ne_zero : D.h3 ≠ 0
  beta1_ne_zero : D.beta1 ≠ 0
  beta2_ne_zero : D.beta2 ≠ 0
  beta3_ne_zero : D.beta3 ≠ 0
  total_trace : trace F K D.origin = -2
  e2_first : elementarySymmetric F K 2 D.origin =
    trace F D.firstField D.a1 + D.beta1
  e2_second : elementarySymmetric F K 2 D.origin =
    trace F D.secondField D.a2 + D.beta2
  e2_third : elementarySymmetric F K 2 D.origin =
    trace F D.thirdField D.a3 + D.beta3

omit [Module.Free F K] in
/-- The lower Galois structure and upper degree on a genuine quadratic edge. -/
private theorem intermediate_quadratic_edges
    (hG : Nonempty
      (Gal(K/F) ≃* (Multiplicative (ZMod 2) × Multiplicative (ZMod 2))))
    (L : IntermediateField F K) (hdegree : Module.finrank F L = 2) :
    IsGalois F L ∧ Module.finrank L K = 2 := by
  obtain ⟨_, _, _, _, _, _, _, _, _, _, hupper, hlower, _⟩ :=
    Basic.intermediateField_tower_compatible Nat.prime_two hG L hdegree
  exact ⟨hlower.1, hupper⟩

omit [Module.Free F K] [IsGalois F K] in
/-- Total ramification gives lower ramification index two and upper residue degree one. -/
private theorem intermediate_quadratic_ramification
    (hres : residueDegree F K = 1)
    (L : IntermediateField F K) (hdegree : Module.finrank F L = 2) :
    letI := Basic.intermediateFieldValuativeRel L
    letI := Basic.intermediateFieldTopology L
    letI := Basic.intermediateField_localField L
    letI := Basic.intermediateField_lowerValuativeExtension L
    letI := Basic.intermediateField_upperValuativeExtension L
    ramificationIndex F L = 2 ∧ residueDegree L K = 1 := by
  letI := Basic.intermediateFieldValuativeRel L
  letI := Basic.intermediateFieldTopology L
  letI := Basic.intermediateField_localField L
  letI := Basic.intermediateField_lowerValuativeExtension L
  letI := Basic.intermediateField_upperValuativeExtension L
  have hmul := intermediate_residueDegree_mul L
  rw [hres] at hmul
  obtain ⟨hlower, hupper⟩ := mul_eq_one.mp hmul
  refine ⟨?_, hupper⟩
  have h := finrank_eq_ramificationIndex_mul_residueDegree F L
  rw [hdegree, hlower, mul_one] at h
  exact h.symm

omit [ValuativeRel K] [TopologicalSpace K] [IsNonarchimedeanLocalField K]
  [ValuativeExtension F K] [Module.Free F K] [Module.Finite F K] [IsGalois F K] in
/-- Alignment controls both error terms, including the extra `2 R²` in the sum. -/
private theorem origin_error_orders
    (htwo : ord F (2 : F) = (e : WithTop ℤ))
    (ha : 1 ≤ a) (hae : a ≤ e) (hb : b = 2 * e - 2 * a + 1)
    (D : AlignmentData pi e a b u0 w0 s R0) :
    (((1 : ℤ) - a : ℤ) : WithTop ℤ) ≤ ord F D.B0 ∧
      (((1 : ℤ) - a : ℤ) : WithTop ℤ) ≤ ord F D.C0 := by
  have hfourOrder : ord F (4 : F) = (((2 * e : ℕ) : ℤ) : WithTop ℤ) := by
    rw [show (4 : F) = 2 * 2 by norm_num, ord_mul, htwo]
    change ((e : ℤ) : WithTop ℤ) + ((e : ℤ) : WithTop ℤ) =
      (((2 * e : ℕ) : ℤ) : WithTop ℤ)
    rw [← WithTop.coe_add]
    apply congrArg
    push_cast
    omega
  have hrs0 : D.rSquare ≠ 0 :=
    (ord_ne_top_iff F).1 (by rw [D.rSquare_order]; exact WithTop.coe_ne_top)
  have hratio : (D.ratio : F) - 1 ∈ lattice F (a : ℤ) := by
    have hm : D.ratio ∈ unitFiltration F ((a - 1) + 1) := by
      simpa only [Nat.sub_add_cancel ha] using D.ratio_mem
    have hm' := (mem_unitFiltration_succ_iff_sub_mem_lattice F (a - 1) D.ratio).1 hm
    simpa only [Nat.sub_add_cancel ha] using hm'
  have hrsMem : D.rSquare ∈ lattice F (b : ℤ) := by
    rw [mem_lattice, D.rSquare_order, natCast_withTop_eq_intCast]
  have hnumEq : D.epsilon - D.rSquare =
      D.rSquare * ((D.ratio : F) - 1) := by
    rw [D.ratio_coe]
    field_simp [hrs0]
  have hnum : D.epsilon - D.rSquare ∈
      lattice F ((b + a : ℕ) : ℤ) := by
    rw [hnumEq]
    simpa only [Nat.cast_add] using mul_mem_lattice F hrsMem hratio
  have hthreshold : ((b + a : ℕ) : ℤ) =
      (2 * (e : ℤ)) + (1 - (a : ℤ)) := by
    push_cast [hb, Nat.cast_sub hae]
    omega
  have hBmem : D.B0 ∈ lattice F (1 - (a : ℤ)) := by
    apply (div_mem_lattice_iff F (4 : F) (D.epsilon - D.rSquare)
      (2 * (e : ℤ)) (1 - (a : ℤ)) (by simpa using hfourOrder)).2
    rw [← hthreshold]
    simpa only [AlignmentData.B0] using hnum
  have htwoR : (2 : F) * D.rSquare ∈
      lattice F ((b + a : ℕ) : ℤ) := by
    rw [mem_lattice, ord_mul, htwo, D.rSquare_order]
    change (((b + a : ℕ) : ℤ) : WithTop ℤ) ≤
      ((e : ℤ) : WithTop ℤ) + ((b : ℤ) : WithTop ℤ)
    rw [← WithTop.coe_add]
    exact WithTop.coe_le_coe.mpr (by push_cast; omega)
  have hplus : D.epsilon + D.rSquare ∈
      lattice F ((b + a : ℕ) : ℤ) := by
    have := add_mem_lattice F hnum htwoR
    convert this using 1
    ring
  have hCmem : D.C0 ∈ lattice F (1 - (a : ℤ)) := by
    apply (div_mem_lattice_iff F (4 : F) (D.epsilon + D.rSquare)
      (2 * (e : ℤ)) (1 - (a : ℤ)) (by simpa using hfourOrder)).2
    rw [← hthreshold]
    simpa only [AlignmentData.C0] using hplus

  exact ⟨(mem_lattice F).1 hBmem, (mem_lattice F).1 hCmem⟩

omit [ValuativeRel K] [TopologicalSpace K] [IsNonarchimedeanLocalField K]
  [ValuativeExtension F K] [Module.Free F K] [Module.Finite F K] [IsGalois F K] in
/-- The aligned square equations inside the three actual intermediate fields. -/
private theorem origin_generator_squares
    (D : AlignmentData pi e a b u0 w0 s R0) :
    D.firstGenerator ^ 2 = algebraMap F D.firstField (1 + D.epsilon) ∧
      D.secondGenerator ^ 2 = algebraMap F D.secondField D.rSquare ∧
      D.thirdGenerator ^ 2 =
        algebraMap F D.thirdField ((1 + D.epsilon) * D.rSquare) := by
  have hS1sq : D.firstGenerator ^ 2 =
      algebraMap F D.firstField (1 + D.epsilon) := by
    apply (algebraMap D.firstField K).injective
    change D.S ^ 2 = algebraMap D.firstField K
      (algebraMap F D.firstField (1 + D.epsilon))
    rw [D.S_sq, ← IsScalarTower.algebraMap_apply F D.firstField K]
  have hR2sq : D.secondGenerator ^ 2 =
      algebraMap F D.secondField D.rSquare := by
    apply (algebraMap D.secondField K).injective
    change D.R ^ 2 = algebraMap D.secondField K
      (algebraMap F D.secondField D.rSquare)
    rw [D.R_sq, ← IsScalarTower.algebraMap_apply F D.secondField K]
  have hthirdSquare : D.thirdGenerator ^ 2 =
      algebraMap F D.thirdField ((1 + D.epsilon) * D.rSquare) := by
    apply (algebraMap D.thirdField K).injective
    change (D.S * D.R) ^ 2 = algebraMap D.thirdField K
      (algebraMap F D.thirdField ((1 + D.epsilon) * D.rSquare))
    rw [← IsScalarTower.algebraMap_apply F D.thirdField K, mul_pow,
      D.S_sq, D.R_sq, map_mul]
  exact ⟨hS1sq, hR2sq, hthirdSquare⟩

/-- The exact table, expressed intrinsically in each intermediate field. -/
private structure OriginTable (D : AlignmentData pi e a b u0 w0 s R0) : Prop where
  a1_eq : D.a1 = (1 - D.firstGenerator) / 2 + algebraMap F D.firstField D.B0
  h1_eq : D.h1 = D.firstGenerator - 1
  beta1_eq : D.beta1 = -D.epsilon
  a2_eq : D.a2 = -D.secondGenerator / 2 - algebraMap F D.secondField D.B0
  h2_eq : D.h2 = D.secondGenerator - 1
  beta2_eq : D.beta2 = 1 - D.rSquare
  a3_eq : D.a3 = -D.thirdGenerator / 2 - algebraMap F D.thirdField D.C0
  h3_eq : D.h3 = -1
  beta3_eq : D.beta3 = 1
  total_trace : trace F K D.origin = -2

omit [Module.Free F K] in
/-- Compute `D:MX:origin-table` using the given nonidentity automorphisms. -/
private theorem origin_norm_trace_table
    (hG : Nonempty
      (Gal(K/F) ≃* (Multiplicative (ZMod 2) × Multiplicative (ZMod 2))))
    (htwo : ord F (2 : F) = (e : WithTop ℤ))
    (D : AlignmentData pi e a b u0 w0 s R0)
    (hdegree1 : Module.finrank F D.firstField = 2)
    (hdegree2 : Module.finrank F D.secondField = 2)
    (hdegree3 : Module.finrank F D.thirdField = 2)
    (g1 : Gal(K/D.firstField)) (hg1 : g1 ≠ 1)
    (hg1R : g1 D.R = -D.R)
    (g2 : Gal(K/D.secondField)) (hg2 : g2 ≠ 1)
    (hg2S : g2 D.S = -D.S)
    (g3 : Gal(K/D.thirdField)) (hg3 : g3 ≠ 1)
    (hg3S : g3 D.S = -D.S) (hg3R : g3 D.R = -D.R)
    (q1 : Gal(D.firstField/F)) (hq1 : q1 ≠ 1)
    (hq1S : q1 D.firstGenerator = -D.firstGenerator)
    (q2 : Gal(D.secondField/F)) (hq2 : q2 ≠ 1)
    (hq2R : q2 D.secondGenerator = -D.secondGenerator) :
    OriginTable D := by
  obtain ⟨hGalois1, hdegree1K⟩ := intermediate_quadratic_edges hG D.firstField hdegree1
  obtain ⟨hGalois2, hdegree2K⟩ := intermediate_quadratic_edges hG D.secondField hdegree2
  obtain ⟨_, hdegree3K⟩ := intermediate_quadratic_edges hG D.thirdField hdegree3
  letI : IsGalois F D.firstField := hGalois1
  letI : IsGalois F D.secondField := hGalois2
  have htwo0 : (2 : F) ≠ 0 :=
    (ord_ne_top_iff F).1 (by rw [htwo]; exact WithTop.coe_ne_top)
  have htwoK : (2 : K) ≠ 0 := by
    intro h
    apply htwo0
    apply (algebraMap F K).injective
    simpa only [map_ofNat, map_zero] using h
  have hfourK : (4 : K) ≠ 0 := by
    rw [show (4 : K) = 2 * 2 by norm_num]
    exact mul_ne_zero htwoK htwoK
  have hg1S : g1 D.S = D.S := by
    change g1 (algebraMap D.firstField K D.firstGenerator) =
      algebraMap D.firstField K D.firstGenerator
    exact g1.commutes D.firstGenerator
  have hg2R : g2 D.R = D.R := by
    change g2 (algebraMap D.secondField K D.secondGenerator) =
      algebraMap D.secondField K D.secondGenerator
    exact g2.commutes D.secondGenerator
  have hg1Y : g1 D.origin = (D.S - D.R - 1) / 2 := by
    simp only [AlignmentData.origin, map_div₀, map_sub, map_add, map_one,
      map_ofNat, hg1S, hg1R]
    ring
  have hg2Y : g2 D.origin = (-D.S + D.R - 1) / 2 := by
    simp only [AlignmentData.origin, map_div₀, map_sub, map_add, map_one,
      map_ofNat, hg2S, hg2R]
  have hg3Y : g3 D.origin = (-D.S - D.R - 1) / 2 := by
    simp only [AlignmentData.origin, map_div₀, map_sub, map_add, map_one,
      map_ofNat, hg3S, hg3R]
    ring

  have ha1Intrinsic : D.a1 =
      (1 - D.firstGenerator) / 2 + algebraMap F D.firstField D.B0 := by
    apply (algebraMap D.firstField K).injective
    simp only [map_add, map_div₀, map_sub, map_one, map_ofNat]
    rw [← IsScalarTower.algebraMap_apply F D.firstField K]
    change algebraMap D.firstField K D.a1 = (1 - D.S) / 2 + algebraMap F K D.B0
    rw [AlignmentData.a1, quadratic_norm_eq g1 hg1 hdegree1K, hg1Y]
    simp only [AlignmentData.origin, AlignmentData.B0, map_div₀, map_sub,
      map_ofNat]
    field_simp [htwoK, hfourK]
    ring_nf
    rw [D.S_sq, D.R_sq, map_add, map_one]
    ring
  have hh1 : D.h1 = D.firstGenerator - 1 := by
    apply (algebraMap D.firstField K).injective
    change algebraMap D.firstField K D.h1 = D.S - 1
    rw [AlignmentData.h1, quadratic_trace_eq g1 hg1 hdegree1K, hg1Y]
    simp only [AlignmentData.origin]
    field_simp [htwoK, hfourK]
    ring
  have ha2Intrinsic : D.a2 =
      -D.secondGenerator / 2 - algebraMap F D.secondField D.B0 := by
    apply (algebraMap D.secondField K).injective
    simp only [map_sub, map_div₀, map_neg, map_ofNat]
    rw [← IsScalarTower.algebraMap_apply F D.secondField K]
    change algebraMap D.secondField K D.a2 = -D.R / 2 - algebraMap F K D.B0
    rw [AlignmentData.a2, quadratic_norm_eq g2 hg2 hdegree2K, hg2Y]
    simp only [AlignmentData.origin, AlignmentData.B0, map_div₀, map_sub,
      map_ofNat]
    field_simp [htwoK, hfourK]
    ring_nf
    rw [D.S_sq, D.R_sq, map_add, map_one]
    ring
  have hh2 : D.h2 = D.secondGenerator - 1 := by
    apply (algebraMap D.secondField K).injective
    change algebraMap D.secondField K D.h2 = D.R - 1
    rw [AlignmentData.h2, quadratic_trace_eq g2 hg2 hdegree2K, hg2Y]
    simp only [AlignmentData.origin]
    field_simp [htwoK, hfourK]
    ring
  have ha3Intrinsic : D.a3 =
      -D.thirdGenerator / 2 - algebraMap F D.thirdField D.C0 := by
    apply (algebraMap D.thirdField K).injective
    simp only [map_sub, map_div₀, map_neg, map_ofNat]
    rw [← IsScalarTower.algebraMap_apply F D.thirdField K]
    change algebraMap D.thirdField K D.a3 = -(D.S * D.R) / 2 - algebraMap F K D.C0
    rw [AlignmentData.a3, quadratic_norm_eq g3 hg3 hdegree3K, hg3Y]
    simp only [AlignmentData.origin, AlignmentData.C0, map_div₀, map_add,
      map_ofNat]
    field_simp [htwoK, hfourK]
    ring_nf
    rw [D.S_sq, D.R_sq, map_add, map_one]
    ring
  have hh3 : D.h3 = -1 := by
    apply (algebraMap D.thirdField K).injective
    simp only [map_neg, map_one]
    change algebraMap D.thirdField K D.h3 = -1
    rw [AlignmentData.h3, quadratic_trace_eq g3 hg3 hdegree3K, hg3Y]
    simp only [AlignmentData.origin]
    field_simp [htwoK, hfourK]
    ring

  obtain ⟨hS1sq, hR2sq, _⟩ := origin_generator_squares D
  have hbeta1 : D.beta1 = -D.epsilon := by
    rw [AlignmentData.beta1, hh1]
    apply (algebraMap F D.firstField).injective
    rw [quadratic_norm_eq q1 hq1 hdegree1, map_sub, hq1S, map_one,
      map_neg]
    ring_nf
    rw [hS1sq, map_add, map_one]
    ring
  have hbeta2 : D.beta2 = 1 - D.rSquare := by
    rw [AlignmentData.beta2, hh2]
    apply (algebraMap F D.secondField).injective
    rw [quadratic_norm_eq q2 hq2 hdegree2, map_sub, hq2R, map_one]
    rw [map_sub, map_one]
    linear_combination -hR2sq
  have hbeta3 : D.beta3 = 1 := by
    rw [AlignmentData.beta3, hh3]
    have hneg : (-1 : D.thirdField) = algebraMap F D.thirdField (-1 : F) := by
      simp
    rw [hneg]
    rw [LanglandsFirstMainLemma.norm_algebraMap, hdegree3]
    norm_num

  have hlowerTrace : trace F D.firstField D.h1 = -2 := by
    apply (algebraMap F D.firstField).injective
    rw [quadratic_trace_eq q1 hq1 hdegree1, hh1, map_sub, hq1S,
      map_one, map_neg, map_ofNat]
    ring
  have htotalTrace : trace F K D.origin = -2 := by
    calc
      trace F K D.origin = trace F D.firstField
          (trace D.firstField K D.origin) := (Algebra.trace_trace D.origin).symm
      _ = trace F D.firstField D.h1 := rfl
      _ = -2 := hlowerTrace

  exact ⟨ha1Intrinsic, hh1, hbeta1, ha2Intrinsic, hh2, hbeta2,
    ha3Intrinsic, hh3, hbeta3, htotalTrace⟩

/-- Adding a base-field error of order at least `1 - a` preserves the leading order. -/
private theorem add_error_order
    {E M : Type*} [Field E] [ValuativeRel E] [TopologicalSpace E]
    [IsNonarchimedeanLocalField E]
    [Field M] [ValuativeRel M] [TopologicalSpace M]
    [IsNonarchimedeanLocalField M]
    [Algebra E M] [ValuativeExtension E M]
    (a : ℕ) (hram : ramificationIndex E M = 2) (x : M) (c : E)
    (hx : ord M x = (((1 : ℤ) - 2 * a : ℤ) : WithTop ℤ))
    (hc : (((1 : ℤ) - a : ℤ) : WithTop ℤ) ≤ ord E c) :
    ord M (x + algebraMap E M c) = (((1 : ℤ) - 2 * a : ℤ) : WithTop ℤ) := by
  have hbound : (((2 : ℤ) * (1 - a : ℤ) : ℤ) : WithTop ℤ) ≤
      ord M (algebraMap E M c) := by
    rw [ord_algebraMap, hram]
    calc
      (((2 : ℤ) * (1 - a : ℤ) : ℤ) : WithTop ℤ) =
          2 • (((1 : ℤ) - a : ℤ) : WithTop ℤ) := by
            rw [← WithTop.coe_nsmul]
            congr 1
      _ ≤ 2 • ord E c := nsmul_le_nsmul_right hc 2
  have hlt : (((1 : ℤ) - 2 * a : ℤ) : WithTop ℤ) <
      ord M (algebraMap E M c) :=
    (WithTop.coe_lt_coe.mpr (by omega)).trans_le hbound
  rw [ord_add_eq_min M (by rw [hx]; exact ne_of_lt hlt), hx, min_eq_left hlt.le]

/-- The normalized orders in `D:MX:valuations`, with all fields explicit. -/
private structure OriginOrders (D : AlignmentData pi e a b u0 w0 s R0) : Prop where
  origin_order : ord K D.origin =
    (((1 : ℤ) - 2 * a : ℤ) : WithTop ℤ)
  a1_order : intermediateOrder D.firstField D.a1 =
    (((1 : ℤ) - 2 * a : ℤ) : WithTop ℤ)
  a2_order : intermediateOrder D.secondField D.a2 =
    (((1 : ℤ) - 2 * a : ℤ) : WithTop ℤ)
  a3_order : intermediateOrder D.thirdField D.a3 =
    (((1 : ℤ) - 2 * a : ℤ) : WithTop ℤ)
  h1_order : intermediateOrder D.firstField D.h1 = (b : WithTop ℤ)
  h2_order : intermediateOrder D.secondField D.h2 = 0
  h3_order : intermediateOrder D.thirdField D.h3 = 0
  beta1_order : ord F D.beta1 = (b : WithTop ℤ)
  beta2_order : ord F D.beta2 = 0
  beta3_order : ord F D.beta3 = 0

omit [Module.Free F K] [IsGalois F K] in
/-- Derive the complete valuation ledger from the exact table and alignment bounds. -/
private theorem origin_orders
    (hres : residueDegree F K = 1)
    (htwo : ord F (2 : F) = (e : WithTop ℤ))
    (ha : 1 ≤ a) (hae : a ≤ e) (hb : b = 2 * e - 2 * a + 1)
    (D : AlignmentData pi e a b u0 w0 s R0)
    (hdegree1 : Module.finrank F D.firstField = 2)
    (hdegree2 : Module.finrank F D.secondField = 2)
    (hdegree3 : Module.finrank F D.thirdField = 2)
    (T : OriginTable D)
    (hB : (((1 : ℤ) - a : ℤ) : WithTop ℤ) ≤ ord F D.B0)
    (hC : (((1 : ℤ) - a : ℤ) : WithTop ℤ) ≤ ord F D.C0) :
    OriginOrders D := by
  letI := Basic.intermediateFieldValuativeRel D.firstField
  letI := Basic.intermediateFieldTopology D.firstField
  letI := Basic.intermediateField_localField D.firstField
  letI := Basic.intermediateField_lowerValuativeExtension D.firstField
  letI := Basic.intermediateField_upperValuativeExtension D.firstField
  letI := Basic.intermediateFieldValuativeRel D.secondField
  letI := Basic.intermediateFieldTopology D.secondField
  letI := Basic.intermediateField_localField D.secondField
  letI := Basic.intermediateField_lowerValuativeExtension D.secondField
  letI := Basic.intermediateField_upperValuativeExtension D.secondField
  letI := Basic.intermediateFieldValuativeRel D.thirdField
  letI := Basic.intermediateFieldTopology D.thirdField
  letI := Basic.intermediateField_localField D.thirdField
  letI := Basic.intermediateField_lowerValuativeExtension D.thirdField
  letI := Basic.intermediateField_upperValuativeExtension D.thirdField
  obtain ⟨hramF1, hres1K⟩ := intermediate_quadratic_ramification hres D.firstField hdegree1
  obtain ⟨hramF2, _⟩ := intermediate_quadratic_ramification hres D.secondField hdegree2
  obtain ⟨hramF3, _⟩ := intermediate_quadratic_ramification hres D.thirdField hdegree3
  obtain ⟨hS1sq, hR2sq, hthirdSquare⟩ := origin_generator_squares D
  have hbpos : 0 < b := by omega
  have honeEpsOrder : ord F (1 + D.epsilon) = 0 := by
    rw [ord_add_eq_min F (by
      rw [ord_one, D.epsilon_order]
      exact ne_of_lt (WithTop.coe_pos.mpr (by exact_mod_cast hbpos))), ord_one,
      D.epsilon_order, min_eq_left]
    exact WithTop.coe_nonneg.mpr (by exact_mod_cast Nat.zero_le b)
  have hthirdBaseOrder : ord F ((1 + D.epsilon) * D.rSquare) =
      (b : WithTop ℤ) := by
    rw [ord_mul, honeEpsOrder, D.rSquare_order, zero_add]
  have hh1Order : ord D.firstField D.h1 = (b : WithTop ℤ) := by
    rw [T.h1_eq]
    exact sqrt_one_sub_order e a b htwo ha hae hb D.epsilon
      D.epsilon_order hramF1 D.firstGenerator hS1sq
  have hR2Order : ord D.secondField D.secondGenerator = (b : WithTop ℤ) :=
    square_root_order b D.rSquare D.rSquare_order hramF2
      D.secondGenerator hR2sq
  have hP3Order : ord D.thirdField D.thirdGenerator = (b : WithTop ℤ) :=
    square_root_order b ((1 + D.epsilon) * D.rSquare) hthirdBaseOrder
      hramF3 D.thirdGenerator hthirdSquare
  have hh2Order : ord D.secondField D.h2 = 0 := by
    rw [T.h2_eq, sub_eq_add_neg, ord_add_eq_min D.secondField (by
      rw [hR2Order, ord_neg, ord_one]
      exact ne_of_gt (WithTop.coe_pos.mpr (by exact_mod_cast hbpos))), hR2Order, ord_neg,
      ord_one, min_eq_right]
    exact WithTop.coe_nonneg.mpr (by exact_mod_cast Nat.zero_le b)
  have hh3Order : ord D.thirdField D.h3 = 0 := by
    rw [T.h3_eq, ord_neg, ord_one]
  have hbeta1Order : ord F D.beta1 = (b : WithTop ℤ) := by
    rw [T.beta1_eq, ord_neg, D.epsilon_order]
  have hbeta2Order : ord F D.beta2 = 0 := by
    rw [T.beta2_eq, sub_eq_add_neg, ord_add_eq_min F (by
      rw [ord_one, ord_neg, D.rSquare_order]
      exact ne_of_lt (WithTop.coe_pos.mpr (by exact_mod_cast hbpos))), ord_one, ord_neg,
      D.rSquare_order, min_eq_left]
    exact WithTop.coe_nonneg.mpr (by exact_mod_cast Nat.zero_le b)
  have hbeta3Order : ord F D.beta3 = 0 := by
    rw [T.beta3_eq, ord_one]

  let targetOrder : WithTop ℤ := (((1 : ℤ) - 2 * a : ℤ) : WithTop ℤ)
  have hlead1 : ord D.firstField ((1 - D.firstGenerator) / 2) =
      targetOrder := by
    apply div_two_order e a b htwo hae hb hramF1
    rw [show 1 - D.firstGenerator = -(D.firstGenerator - 1) by ring,
      ord_neg, ← T.h1_eq]
    exact hh1Order
  have hlead2 : ord D.secondField (-D.secondGenerator / 2) =
      targetOrder := by
    apply div_two_order e a b htwo hae hb hramF2
    rw [ord_neg, hR2Order]
  have hlead3 : ord D.thirdField (-D.thirdGenerator / 2) =
      targetOrder := by
    apply div_two_order e a b htwo hae hb hramF3
    rw [ord_neg, hP3Order]

  have ha1Order : ord D.firstField D.a1 = targetOrder := by
    rw [T.a1_eq]
    exact add_error_order a hramF1 _ _ hlead1 hB
  have ha2Order : ord D.secondField D.a2 = targetOrder := by
    rw [T.a2_eq, sub_eq_add_neg, ← map_neg]
    exact add_error_order a hramF2 _ _ hlead2 (by simpa only [ord_neg] using hB)
  have ha3Order : ord D.thirdField D.a3 = targetOrder := by
    rw [T.a3_eq, sub_eq_add_neg, ← map_neg]
    exact add_error_order a hramF3 _ _ hlead3 (by simpa only [ord_neg] using hC)
  have horiginOrder : ord K D.origin = targetOrder := by
    have hn := ord_norm D.firstField K D.origin
    rw [hres1K, one_nsmul] at hn
    change ord D.firstField D.a1 = ord K D.origin at hn
    exact hn.symm.trans ha1Order

  exact ⟨horiginOrder, ha1Order, ha2Order, ha3Order, hh1Order, hh2Order, hh3Order,
    hbeta1Order, hbeta2Order, hbeta3Order⟩

/-- A finite normalized order certifies that its argument is nonzero. -/
private theorem ne_zero_of_order_eq
    {E : Type*} [Field E] [ValuativeRel E] [TopologicalSpace E]
    [IsNonarchimedeanLocalField E] {x : E} {z : ℤ}
    (hx : ord E x = (z : WithTop ℤ)) : x ≠ 0 :=
  (ord_ne_top_iff E).1 (hx.trans_ne WithTop.coe_ne_top)

omit [Module.Free F K] [IsGalois F K] in
/-- The same nonvanishing criterion for the intrinsic order on an intermediate field. -/
private theorem ne_zero_of_intermediateOrder_eq
    (L : IntermediateField F K) {x : L} {z : ℤ}
    (hx : intermediateOrder L x = (z : WithTop ℤ)) : x ≠ 0 := by
  letI := Basic.intermediateFieldValuativeRel L
  letI := Basic.intermediateFieldTopology L
  letI := Basic.intermediateField_localField L
  exact ne_zero_of_order_eq hx

/-- Apply the biquadratic `E₂` identity on any of the three genuine quadratic fields. -/
private theorem origin_e2
    (hG : Nonempty
      (Gal(K/F) ≃* (Multiplicative (ZMod 2) × Multiplicative (ZMod 2))))
    (L : IntermediateField F K) (hdegree : Module.finrank F L = 2) (x : K) :
    elementarySymmetric F K 2 x = trace F L (norm L K x) + norm F L (trace L K x) := by
  obtain ⟨_, hupper⟩ := intermediate_quadratic_edges hG L hdegree
  let iso := Classical.choice hG
  letI : IsKleinFour Gal(K/F) := by
    constructor
    · rw [Nat.card_congr iso.toEquiv, Nat.card_prod]
      norm_num
    · rw [Monoid.exponent_eq_of_mulEquiv iso, Monoid.exponent_prod]
      norm_num
  letI : Algebra.IsQuadraticExtension F L := ⟨hdegree⟩
  letI : Algebra.IsQuadraticExtension L K := ⟨hupper⟩
  exact LanglandsSecondMainLemma.Algebra.biquadraticE2 F K L x

set_option maxHeartbeats 800000 in
/-- **Aligned Kummer origin (`D:MX:origin`--`D:MX:valuations`).**

The input automorphisms are the actual nonidentity automorphisms on the
six quadratic edges.  Their displayed actions say precisely which Kummer
generator each edge fixes; these facts are supplied by the genuine
three-field diagram, not by an abstract norm model.  From them, the theorem
constructs the actual norm and trace entries and proves the complete table,
all nonzero assertions, and all normalized orders. -/
theorem dyadicMaximal_origin_data
    (hG : Nonempty
      (Gal(K/F) ≃* (Multiplicative (ZMod 2) × Multiplicative (ZMod 2))))
    (hres : residueDegree F K = 1)
    (htwo : ord F (2 : F) = (e : WithTop ℤ))
    (ha : 1 ≤ a) (hae : a ≤ e) (hb : b = 2 * e - 2 * a + 1)
    (D : AlignmentData pi e a b u0 w0 s R0)
    (hdegree1 : Module.finrank F D.firstField = 2)
    (hdegree2 : Module.finrank F D.secondField = 2)
    (hdegree3 : Module.finrank F D.thirdField = 2)
    (g1 : Gal(K/D.firstField)) (hg1 : g1 ≠ 1)
    (hg1R : g1 D.R = -D.R)
    (g2 : Gal(K/D.secondField)) (hg2 : g2 ≠ 1)
    (hg2S : g2 D.S = -D.S)
    (g3 : Gal(K/D.thirdField)) (hg3 : g3 ≠ 1)
    (hg3S : g3 D.S = -D.S) (hg3R : g3 D.R = -D.R)
    (q1 : Gal(D.firstField/F)) (hq1 : q1 ≠ 1)
    (hq1S : q1 D.firstGenerator = -D.firstGenerator)
    (q2 : Gal(D.secondField/F)) (hq2 : q2 ≠ 1)
    (hq2R : q2 D.secondGenerator = -D.secondGenerator) :
    OriginData D := by
  obtain ⟨hB, hC⟩ := origin_error_orders htwo ha hae hb D
  have T := origin_norm_trace_table hG htwo D hdegree1 hdegree2 hdegree3
    g1 hg1 hg1R g2 hg2 hg2S g3 hg3 hg3S hg3R q1 hq1 hq1S q2 hq2 hq2R
  have O := origin_orders hres htwo ha hae hb D hdegree1 hdegree2 hdegree3 T hB hC
  refine {
    first_degree := hdegree1
    second_degree := hdegree2
    third_degree := hdegree3
    B0_order := hB
    C0_order := hC
    a1_table := ?_
    h1_table := ?_
    beta1_table := T.beta1_eq
    a2_table := ?_
    h2_table := ?_
    beta2_table := T.beta2_eq
    a3_table := ?_
    h3_table := ?_
    beta3_table := T.beta3_eq
    origin_order := O.origin_order
    a1_order := O.a1_order
    a2_order := O.a2_order
    a3_order := O.a3_order
    h1_order := O.h1_order
    h2_order := O.h2_order
    h3_order := O.h3_order
    beta1_order := O.beta1_order
    beta2_order := O.beta2_order
    beta3_order := O.beta3_order
    origin_ne_zero := ne_zero_of_order_eq O.origin_order
    a1_ne_zero := ne_zero_of_intermediateOrder_eq D.firstField O.a1_order
    a2_ne_zero := ne_zero_of_intermediateOrder_eq D.secondField O.a2_order
    a3_ne_zero := ne_zero_of_intermediateOrder_eq D.thirdField O.a3_order
    h1_ne_zero := ne_zero_of_intermediateOrder_eq D.firstField O.h1_order
    h2_ne_zero := ne_zero_of_intermediateOrder_eq D.secondField O.h2_order
    h3_ne_zero := ne_zero_of_intermediateOrder_eq D.thirdField O.h3_order
    beta1_ne_zero := ne_zero_of_order_eq O.beta1_order
    beta2_ne_zero := ne_zero_of_order_eq O.beta2_order
    beta3_ne_zero := ne_zero_of_order_eq O.beta3_order
    total_trace := T.total_trace
    e2_first := origin_e2 hG D.firstField hdegree1 D.origin
    e2_second := origin_e2 hG D.secondField hdegree2 D.origin
    e2_third := origin_e2 hG D.thirdField hdegree3 D.origin }
  · simp only [T.a1_eq, map_add, map_div₀, map_sub, map_one, map_ofNat,
      ← IsScalarTower.algebraMap_apply F D.firstField K]
    rfl
  · simp only [T.h1_eq, map_sub, map_one]
    rfl
  · simp only [T.a2_eq, map_sub, map_div₀, map_neg, map_ofNat,
      ← IsScalarTower.algebraMap_apply F D.secondField K]
    rfl
  · simp only [T.h2_eq, map_sub, map_one]
    rfl
  · simp only [T.a3_eq, map_sub, map_div₀, map_neg, map_ofNat,
      ← IsScalarTower.algebraMap_apply F D.thirdField K]
    rfl
  · simp only [T.h3_eq, map_neg, map_one]

end

end LanglandsSecondMainLemma.Dyadic.Maximal
