import LanglandsFirstMainLemma.FiniteField.ArtinSchreier
import LanglandsFirstMainLemma.FiniteField.FrobeniusTrace
import LanglandsFirstMainLemma.FiniteField.QuadraticPhase
import LanglandsFirstMainLemma.Ramification.Different
import LanglandsFirstMainLemma.Ramification.LowerGroups
import LanglandsFirstMainLemma.Ramification.NormFiltration
import LanglandsFirstMainLemma.Ramification.SymmetricBounds
import LanglandsSecondMainLemma.Ramification.UnramifiedPart

/-!
# Ramification / Inertia Coefficients

This file formalizes the second paragraph of the proof of Paper Lemma D.2. It constructs a
uniformizer that is monogenic over the actual inertia fixed field, bundles the tame
multiplicative and positive-depth additive residue coefficients as homomorphisms, and proves
their exact kernels. The resulting tame quotient is cyclic of order prime to the residue
characteristic, while the positive-depth maps and eventual triviality of the lower filtration
show that wild inertia is a `p`-group.
-/

namespace LanglandsSecondMainLemma.Ramification

open LanglandsFirstMainLemma
open scoped Pointwise

noncomputable section

variable {F K : Type*} [Field F] [Field K]
variable [ValuativeRel F] [TopologicalSpace F] [IsNonarchimedeanLocalField F]
variable [ValuativeRel K] [TopologicalSpace K] [IsNonarchimedeanLocalField K]
variable [Algebra F K] [ValuativeExtension F K] [Module.Finite F K]
variable [IsGalois F K]

/-- The two genuine residue actions used by SML and FML have the same kernel. -/
theorem inertiaSubgroup_eq_lowerRamificationGroup_zero :
    inertiaSubgroup (F := F) (K := K) = lowerRamificationGroup F K 0 := by
  rw [lowerRamificationGroup_zero_eq_ker_galoisResidueAction]
  ext σ
  simp only [inertiaSubgroup, MonoidHom.mem_ker]
  constructor
  · intro hσ
    apply RingEquiv.ext
    intro z
    obtain ⟨x, rfl⟩ := residueMap_surjective K z
    rw [galoisResidueAction_residue]
    calc
      residueMap K (galoisIntegerEquiv F K σ x) =
          residueAction (F := F) (K := K) σ (residueMap K x) := by
        rw [residueAction_apply_residue]
      _ = residueMap K x := by rw [hσ]; rfl
      _ = (1 : RingAut (ResidueField K)) (residueMap K x) := rfl
  · intro hσ
    apply AlgEquiv.ext
    intro z
    obtain ⟨x, rfl⟩ := residueMap_surjective K z
    rw [residueAction_apply_residue]
    calc
      residueMap K (galoisIntegerEquiv F K σ x) =
          galoisResidueAction F K σ (residueMap K x) := by
        rw [galoisResidueAction_residue]
      _ = residueMap K x := by rw [hσ]; rfl
      _ = (1 : Gal(ResidueField K / ResidueField F)) (residueMap K x) := rfl

/-- The residue map of the intermediate field generated by a primitive residue lift is onto. -/
private theorem intermediate_residue_surjective_from_generator
    (a : ringOfIntegers K)
    (hprimitive :
      IntermediateField.adjoin (ResidueField F) {residueMap K a} = ⊤) :
    let E : IntermediateField F K := IntermediateField.adjoin F {(a : K)}
    letI : ValuativeRel E := Basic.intermediateFieldValuativeRel E
    letI : TopologicalSpace E := Basic.intermediateFieldTopology E
    letI : IsNonarchimedeanLocalField E := Basic.intermediateField_localField E
    letI : ValuativeExtension F E := Basic.intermediateField_lowerValuativeExtension E
    letI : ValuativeExtension E K := Basic.intermediateField_upperValuativeExtension E
    Function.Surjective (algebraMap (ResidueField E) (ResidueField K)) := by
  dsimp only
  let E : IntermediateField F K := IntermediateField.adjoin F {(a : K)}
  letI : ValuativeRel E := Basic.intermediateFieldValuativeRel E
  letI : TopologicalSpace E := Basic.intermediateFieldTopology E
  letI : IsNonarchimedeanLocalField E := Basic.intermediateField_localField E
  letI : ValuativeExtension F E := Basic.intermediateField_lowerValuativeExtension E
  letI : ValuativeExtension E K := Basic.intermediateField_upperValuativeExtension E
  letI : IsScalarTower
      (ringOfIntegers F) (ringOfIntegers E) (ringOfIntegers K) :=
    IsScalarTower.of_algebraMap_eq' (by
      ext x
      change algebraMap F K (x : F) = algebraMap E K (algebraMap F E (x : F))
      rw [← IsScalarTower.algebraMap_apply F E K])
  letI : IsLocalHom
      (algebraMap (ringOfIntegers F) (ringOfIntegers E)) := inferInstance
  letI : IsLocalHom
      (algebraMap (ringOfIntegers F) (ringOfIntegers K)) := inferInstance
  let ι : ResidueField E →ₐ[ResidueField F] ResidueField K :=
    IsScalarTower.toAlgHom (ResidueField F) (ResidueField E) (ResidueField K)
  let aE : E := ⟨(a : K),
    IntermediateField.subset_adjoin F {(a : K)} (Set.mem_singleton (a : K))⟩
  have haEint : aE ∈ ringOfIntegers E :=
    (Basic.mem_intermediateField_canonicalRingOfIntegers_iff E aE).2 a.property
  let aOE : ringOfIntegers E := ⟨aE, haEint⟩
  have hgenMem : residueMap K a ∈ ι.fieldRange := by
    apply (AlgHom.mem_fieldRange).2
    refine ⟨residueMap E aOE, ?_⟩
    dsimp only [ι]
    change algebraMap (ResidueField E) (ResidueField K) (residueMap E aOE) = _
    rw [IsLocalRing.ResidueField.algebraMap_residue]
    rfl
  have hadjoin :
      IntermediateField.adjoin (ResidueField F) {residueMap K a} ≤
        ι.fieldRange := by
    apply IntermediateField.adjoin_le_iff.mpr
    intro x hx
    simp only [Set.mem_singleton_iff] at hx
    subst x
    exact hgenMem
  have hrange : ι.fieldRange = ⊤ := by
    apply top_unique
    rw [← hprimitive]
    exact hadjoin
  have hι : Function.Surjective ι := AlgHom.fieldRange_eq_top.mp hrange
  intro x
  obtain ⟨y, hy⟩ := hι x
  exact ⟨y, by simpa [ι] using hy⟩

/-- There is a uniformizer of `K` that generates its integers over the actual inertia fixed
field. This is constructed from the maximal unramified field, not postulated. -/
theorem exists_inertiaUniformizer :
    ∃ (E : IntermediateField F K),
      E = IntermediateField.fixedField (inertiaSubgroup (F := F) (K := K)) ∧
      letI : ValuativeRel E := Basic.intermediateFieldValuativeRel E
      letI : TopologicalSpace E := Basic.intermediateFieldTopology E
      letI : IsNonarchimedeanLocalField E := Basic.intermediateField_localField E
      letI : ValuativeExtension E K := Basic.intermediateField_upperValuativeExtension E
      residueDegree E K = 1 ∧
        ∃ π : ringOfIntegers K,
          (ValuativeRel.valuation K).IsUniformizer (π : K) ∧
            Algebra.adjoin (ringOfIntegers E) ({π} : Set (ringOfIntegers K)) = ⊤ := by
  obtain ⟨a, P, hPmonic, hPred, hprimitive, haRoot, hfixed, _⟩ :=
    maximalUnramified_fixedField (F := F) (K := K)
  let E : IntermediateField F K := IntermediateField.adjoin F {(a : K)}
  refine ⟨E, hfixed, ?_⟩
  letI : ValuativeRel E := Basic.intermediateFieldValuativeRel E
  letI : TopologicalSpace E := Basic.intermediateFieldTopology E
  letI : IsNonarchimedeanLocalField E := Basic.intermediateField_localField E
  letI : ValuativeExtension E K := Basic.intermediateField_upperValuativeExtension E
  letI : Module.Free (ResidueField E) (ResidueField K) :=
    Module.Free.of_divisionRing (ResidueField E) (ResidueField K)
  have hsurj : Function.Surjective
      (algebraMap (ResidueField E) (ResidueField K)) :=
    intermediate_residue_surjective_from_generator (F := F) (K := K) a hprimitive
  have hresidue : residueDegree E K = 1 := by
    rw [residueDegree_eq_finrank_residueField]
    exact Algebra.finrank_eq_one_iff_bijective_algebraMap.mpr
      ⟨(algebraMap (ResidueField E) (ResidueField K)).injective, hsurj⟩
  exact ⟨hresidue,
    exists_uniformizer_and_algebra_adjoin_eq_top_of_residueDegree_eq_one E K hresidue⟩

/-- A chosen realization of the maximal unramified field used to obtain a monogenic
uniformizer for the inertia extension. -/
noncomputable def inertiaFixedField : IntermediateField F K :=
  (exists_inertiaUniformizer (F := F) (K := K)).choose

@[simp]
theorem inertiaFixedField_eq_fixedField :
    inertiaFixedField (F := F) (K := K) =
      IntermediateField.fixedField (inertiaSubgroup (F := F) (K := K)) :=
  (exists_inertiaUniformizer (F := F) (K := K)).choose_spec.1

theorem inertiaFixedField_residueDegree :
    let E := inertiaFixedField (F := F) (K := K)
    letI : ValuativeRel E := Basic.intermediateFieldValuativeRel E
    letI : TopologicalSpace E := Basic.intermediateFieldTopology E
    letI : IsNonarchimedeanLocalField E := Basic.intermediateField_localField E
    letI : ValuativeExtension E K := Basic.intermediateField_upperValuativeExtension E
    residueDegree E K = 1 :=
  (exists_inertiaUniformizer (F := F) (K := K)).choose_spec.2.1

/-- The chosen uniformizer of `K`, monogenic over the actual inertia fixed field. -/
noncomputable def inertiaUniformizer : ringOfIntegers K := by
  let E := inertiaFixedField (F := F) (K := K)
  letI : ValuativeRel E := Basic.intermediateFieldValuativeRel E
  letI : TopologicalSpace E := Basic.intermediateFieldTopology E
  letI : IsNonarchimedeanLocalField E := Basic.intermediateField_localField E
  letI : ValuativeExtension E K := Basic.intermediateField_upperValuativeExtension E
  exact (exists_inertiaUniformizer (F := F) (K := K)).choose_spec.2.2.choose

theorem inertiaUniformizer_isUniformizer :
    (ValuativeRel.valuation K).IsUniformizer
      (inertiaUniformizer (F := F) (K := K) : K) := by
  let E := inertiaFixedField (F := F) (K := K)
  letI : ValuativeRel E := Basic.intermediateFieldValuativeRel E
  letI : TopologicalSpace E := Basic.intermediateFieldTopology E
  letI : IsNonarchimedeanLocalField E := Basic.intermediateField_localField E
  letI : ValuativeExtension E K := Basic.intermediateField_upperValuativeExtension E
  exact (exists_inertiaUniformizer (F := F) (K := K)).choose_spec.2.2.choose_spec.1

theorem inertiaUniformizer_adjoin_eq_top :
    let E := inertiaFixedField (F := F) (K := K)
    letI : ValuativeRel E := Basic.intermediateFieldValuativeRel E
    letI : TopologicalSpace E := Basic.intermediateFieldTopology E
    letI : IsNonarchimedeanLocalField E := Basic.intermediateField_localField E
    letI : ValuativeExtension E K := Basic.intermediateField_upperValuativeExtension E
    Algebra.adjoin (ringOfIntegers E)
      ({inertiaUniformizer (F := F) (K := K)} : Set (ringOfIntegers K)) = ⊤ := by
  dsimp only
  exact (exists_inertiaUniformizer (F := F) (K := K)).choose_spec.2.2.choose_spec.2

/-- On inertia, congruence on the chosen monogenic uniformizer tests the complete lower
ramification condition. -/
theorem mem_lowerRamificationGroup_iff_inertiaUniformizer
    (σ : lowerRamificationGroup F K 0) (i : ℤ) :
    (σ : Gal(K/F)) ∈ lowerRamificationGroup F K i ↔
      CongruentAtDepth (i + 1)
        ((σ : Gal(K/F)) (inertiaUniformizer (F := F) (K := K) : K))
        (inertiaUniformizer (F := F) (K := K) : K) := by
  let E := inertiaFixedField (F := F) (K := K)
  letI : ValuativeRel E := Basic.intermediateFieldValuativeRel E
  letI : TopologicalSpace E := Basic.intermediateFieldTopology E
  letI : IsNonarchimedeanLocalField E := Basic.intermediateField_localField E
  letI : ValuativeExtension E K := Basic.intermediateField_upperValuativeExtension E
  let π := inertiaUniformizer (F := F) (K := K)
  have hgen : Algebra.adjoin (ringOfIntegers E)
      ({π} : Set (ringOfIntegers K)) = ⊤ :=
    inertiaUniformizer_adjoin_eq_top (F := F) (K := K)
  constructor
  · intro hσ
    exact (mem_lowerRamificationGroup F K (σ : Gal(K/F)) i).1 hσ π
  · intro hπ
    rw [mem_lowerRamificationGroup]
    intro x
    have hx : x ∈ Algebra.adjoin (ringOfIntegers E)
        ({π} : Set (ringOfIntegers K)) := by
      rw [hgen]
      trivial
    exact Algebra.adjoin_induction (p := fun (z : ringOfIntegers K) _ =>
        CongruentAtDepth (i + 1) ((σ : Gal(K/F)) (z : K)) (z : K))
      (fun z hz => by
        rw [Set.mem_singleton_iff.mp hz]
        exact hπ)
      (fun r => by
        have hσI : (σ : Gal(K/F)) ∈ inertiaSubgroup (F := F) (K := K) := by
          rw [inertiaSubgroup_eq_lowerRamificationGroup_zero]
          exact σ.prop
        have hrmem : ((r : E) : K) ∈
            IntermediateField.fixedField
              (inertiaSubgroup (F := F) (K := K)) := by
          rw [← inertiaFixedField_eq_fixedField (F := F) (K := K)]
          exact r.val.property
        have hrfix : (σ : Gal(K/F)) ((r : E) : K) = ((r : E) : K) :=
          (IntermediateField.mem_fixedField_iff
              (inertiaSubgroup (F := F) (K := K)) ((r : E) : K)).mp hrmem
            (σ : Gal(K/F)) hσI
        have heq :
            (σ : Gal(K/F))
                (((algebraMap (ringOfIntegers E) (ringOfIntegers K) r) :
                  ringOfIntegers K) : K) =
              (((algebraMap (ringOfIntegers E) (ringOfIntegers K) r) :
                ringOfIntegers K) : K) := by
          simpa using hrfix
        rw [heq]
        exact CongruentAtDepth.refl _)
      (fun a b _ _ ha hb => by
        simpa only [map_add, Subring.coe_add] using ha.add hb)
      (fun a b _ _ ha hb => by
        have hσa : (0 : WithTop ℤ) ≤ ord K ((σ : Gal(K/F)) (a : K)) :=
          (ord_nonneg_iff_mem_integer K _).2
            ((galoisConjugate_mem_ringOfIntegers_iff F K (σ : Gal(K/F)) (a : K)).2
              a.prop)
        have hb0 : (0 : WithTop ℤ) ≤ ord K (b : K) :=
          (ord_nonneg_iff_mem_integer K _).2 b.prop
        simpa only [map_mul, Subring.coe_mul] using ha.mul hσa hb0 hb)
      hx

omit [IsGalois F K] in
private theorem galois_mem_lattice_zero
    (σ : Gal(K/F)) {x : K} (hx : x ∈ lattice K 0) :
    σ x ∈ lattice K 0 := by
  rw [mem_lattice, ord_galoisConjugate]
  exact hx

omit [IsGalois F K] in
private theorem reduce_galois_of_mem_lowerRamificationGroup_zero
    (σ : lowerRamificationGroup F K 0) {x : K} (hx : x ∈ lattice K 0) :
    reduce K ((σ : Gal(K/F)) x)
        (galois_mem_lattice_zero (F := F) (K := K) (σ : Gal(K/F)) hx) =
      reduce K x hx := by
  have hσ : galoisResidueAction F K (σ : Gal(K/F)) = 1 := by
    rw [← MonoidHom.mem_ker, ← lowerRamificationGroup_zero_eq_ker_galoisResidueAction]
    exact σ.prop
  change residueMap K
      (galoisIntegerEquiv F K (σ : Gal(K/F))
        ⟨x, (mem_lattice_zero_iff K).1 hx⟩) =
    residueMap K ⟨x, (mem_lattice_zero_iff K).1 hx⟩
  rw [← galoisResidueAction_residue, hσ]
  rfl

private theorem reduce_mul
    {x y : K} (hx : x ∈ lattice K 0) (hy : y ∈ lattice K 0) :
    reduce K (x * y) (by simpa using mul_mem_lattice K hx hy) =
      reduce K x hx * reduce K y hy := by
  change residueMap K
      ⟨x * y, (mem_lattice_zero_iff K).1 (by simpa using mul_mem_lattice K hx hy)⟩ =
    residueMap K ⟨x, (mem_lattice_zero_iff K).1 hx⟩ *
      residueMap K ⟨y, (mem_lattice_zero_iff K).1 hy⟩
  rw [← map_mul]
  rfl

private theorem reduce_eq_of_eq
    {x y : K} (hx : x ∈ lattice K 0) (hy : y ∈ lattice K 0) (hxy : x = y) :
    reduce K x hx = reduce K y hy := by
  subst y
  rfl

private theorem reduce_add
    {x y : K} (hx : x ∈ lattice K 0) (hy : y ∈ lattice K 0) :
    reduce K (x + y) ((lattice K 0).add_mem hx hy) =
      reduce K x hx + reduce K y hy := by
  change residueMap K
      ⟨x + y, (mem_lattice_zero_iff K).1 ((lattice K 0).add_mem hx hy)⟩ =
    residueMap K ⟨x, (mem_lattice_zero_iff K).1 hx⟩ +
      residueMap K ⟨y, (mem_lattice_zero_iff K).1 hy⟩
  rw [← map_add]
  rfl

private theorem reduce_pow
    {x : K} (hx : x ∈ lattice K 0) (n : ℕ)
    (hxpow : x ^ n ∈ lattice K 0) :
    reduce K (x ^ n) hxpow = (reduce K x hx) ^ n := by
  change residueMap K
      ⟨x ^ n, (mem_lattice_zero_iff K).1 hxpow⟩ =
    (residueMap K ⟨x, (mem_lattice_zero_iff K).1 hx⟩) ^ n
  rw [← map_pow]
  rfl

/-- The manuscript's multiplicative coefficient map on the zeroth lower group. -/
noncomputable def tameInertiaHom :
    lowerRamificationGroup F K 0 →* (ResidueField K)ˣ where
  toFun σ := lowerRamificationTameResidueUnit F K σ
    (inertiaUniformizer (F := F) (K := K) : K)
    (inertiaUniformizer_isUniformizer (F := F) (K := K))
  map_one' := by
    let π : K := inertiaUniformizer (F := F) (K := K)
    let hπ := inertiaUniformizer_isUniformizer (F := F) (K := K)
    have hone : (1 : K) ∈ lattice K 0 := by simp
    apply Units.ext
    rw [coe_lowerRamificationTameResidueUnit]
    unfold lowerRamificationTameResidue
    calc
      reduce K
          (lowerRamificationTameRatio F K
            (1 : lowerRamificationGroup F K 0) π hπ : K) _ =
          reduce K 1 hone := by
        apply reduce_eq_of_eq (K := K)
        rw [coe_lowerRamificationTameRatio]
        exact div_self hπ.ne_zero
      _ = 1 := rfl
  map_mul' σ τ := by
    let π : K := inertiaUniformizer (F := F) (K := K)
    let hπ := inertiaUniformizer_isUniformizer (F := F) (K := K)
    let rσ := lowerRamificationTameRatio F K σ π hπ
    let rτ := lowerRamificationTameRatio F K τ π hπ
    let rστ := lowerRamificationTameRatio F K (σ * τ) π hπ
    have hrτg : (σ : Gal(K/F)) (rτ : K) ∈ lattice K 0 :=
      galois_mem_lattice_zero (F := F) (K := K) (σ : Gal(K/F)) rτ.prop
    have hprod : (σ : Gal(K/F)) (rτ : K) * (rσ : K) ∈ lattice K 0 := by
      simpa using mul_mem_lattice K hrτg rσ.prop
    have hfield : (rστ : K) = (σ : Gal(K/F)) (rτ : K) * (rσ : K) := by
      change ((σ * τ : lowerRamificationGroup F K 0) : Gal(K/F)) π / π =
        (σ : Gal(K/F)) ((τ : Gal(K/F)) π / π) *
          ((σ : Gal(K/F)) π / π)
      rw [Subgroup.coe_mul, AlgEquiv.mul_apply, map_div₀]
      exact (div_mul_div_cancel₀
        ((map_ne_zero (σ : Gal(K/F))).2 hπ.ne_zero)).symm
    apply Units.ext
    change reduce K (rστ : K) rστ.prop =
      reduce K (rσ : K) rσ.prop * reduce K (rτ : K) rτ.prop
    calc
      reduce K (rστ : K) rστ.prop =
          reduce K ((σ : Gal(K/F)) (rτ : K) * (rσ : K)) hprod := by
        exact reduce_eq_of_eq (K := K) rστ.prop hprod hfield
      _ = reduce K ((σ : Gal(K/F)) (rτ : K)) hrτg *
          reduce K (rσ : K) rσ.prop :=
        reduce_mul (K := K) hrτg rσ.prop
      _ = reduce K (rτ : K) rτ.prop * reduce K (rσ : K) rσ.prop := by
        rw [reduce_galois_of_mem_lowerRamificationGroup_zero
          (F := F) (K := K) σ rτ.prop]
      _ = reduce K (rσ : K) rσ.prop * reduce K (rτ : K) rτ.prop := mul_comm _ _

private theorem tameResidue_eq_one_iff_congruent
    (σ : lowerRamificationGroup F K 0) :
    lowerRamificationTameResidue F K σ
        (inertiaUniformizer (F := F) (K := K) : K)
        (inertiaUniformizer_isUniformizer (F := F) (K := K)) = 1 ↔
      CongruentAtDepth 2
        ((σ : Gal(K/F)) (inertiaUniformizer (F := F) (K := K) : K))
        (inertiaUniformizer (F := F) (K := K) : K) := by
  let π := inertiaUniformizer (F := F) (K := K)
  let hπ := inertiaUniformizer_isUniformizer (F := F) (K := K)
  let z := lowerRamificationTameRatio F K σ (π : K) hπ
  change residueMap K
      ⟨(z : K), (mem_lattice_zero_iff K).1 z.prop⟩ = residueMap K 1 ↔ _
  rw [residueMap_eq_residueMap_iff]
  change ((σ : Gal(K/F)) (π : K) / (π : K) - 1) ∈ lattice K 1 ↔ _
  rw [div_sub_one hπ.ne_zero]
  rw [div_mem_lattice_iff K (π : K)
    ((σ : Gal(K/F)) (π : K) - (π : K)) 1 1 (ord_uniformizer K hπ)]
  exact (congruentAtDepth_iff_sub_mem_lattice K 2
    ((σ : Gal(K/F)) (π : K)) (π : K)).symm

/-- The tame coefficient is one exactly on the first lower ramification group. -/
@[simp]
theorem tameInertiaHom_eq_one_iff
    (σ : lowerRamificationGroup F K 0) :
    tameInertiaHom (F := F) (K := K) σ = 1 ↔
      (σ : Gal(K/F)) ∈ lowerRamificationGroup F K 1 := by
  rw [mem_lowerRamificationGroup_iff_inertiaUniformizer
    (F := F) (K := K) σ 1]
  change lowerRamificationTameResidueUnit F K σ
      (inertiaUniformizer (F := F) (K := K) : K)
      (inertiaUniformizer_isUniformizer (F := F) (K := K)) = 1 ↔ _
  rw [Units.ext_iff]
  exact tameResidue_eq_one_iff_congruent (F := F) (K := K) σ

/-- Exact kernel of the tame multiplicative coefficient map. -/
theorem tameInertiaHom_ker :
    (tameInertiaHom (F := F) (K := K)).ker =
      lowerRamificationGroupInside F K (show (0 : ℤ) ≤ 1 by omega) := by
  ext σ
  rw [MonoidHom.mem_ker, tameInertiaHom_eq_one_iff,
    mem_lowerRamificationGroupInside]

/-- The tame quotient is identified with the actual finite subgroup cut out by the
multiplicative coefficient map. -/
noncomputable def tameInertiaQuotientEquivRange :
    LowerRamificationGraded F K 0 ≃*
      (tameInertiaHom (F := F) (K := K)).range :=
  (QuotientGroup.quotientMulEquivOfEq
      (tameInertiaHom_ker (F := F) (K := K)).symm).trans
    (QuotientGroup.quotientKerEquivRange
      (tameInertiaHom (F := F) (K := K)))

/-- The tame inertia quotient `G₀/G₁ = I/G₁` is cyclic, and its order is prime to the
residue characteristic. -/
theorem tameInertia_cyclic :
    IsCyclic (LowerRamificationGraded F K 0) ∧
      Nat.Coprime (Nat.card (LowerRamificationGraded F K 0))
        (residueCharacteristic F) := by
  let f := tameInertiaHom (F := F) (K := K)
  let e := tameInertiaQuotientEquivRange (F := F) (K := K)
  have hcyclic : IsCyclic (LowerRamificationGraded F K 0) := by
    letI : IsCyclic f.range := inferInstance
    exact isCyclic_of_injective e.toMonoidHom e.injective
  refine ⟨hcyclic, ?_⟩
  rw [← residueCharacteristic_extension_eq F K]
  let p := residueCharacteristic K
  letI : Fact p.Prime := ⟨residueCharacteristic_prime K⟩
  letI : Fintype (ResidueField K) := Fintype.ofFinite (ResidueField K)
  have hpdiv : p ∣ Nat.card (ResidueField K) := by
    rw [Nat.card_eq_fintype_card]
    exact (prime_dvd_char_iff_dvd_card p).mp (dvd_refl p)
  have hcardpos : 1 ≤ Nat.card (ResidueField K) := Nat.card_pos
  have hunits : Nat.Coprime (Nat.card (ResidueField K)ˣ) p := by
    rw [Nat.card_units]
    exact ((Nat.coprime_self_sub_left hcardpos).2 (by simp)).of_dvd_right hpdiv
  have hrange : Nat.Coprime (Nat.card f.range) p :=
    hunits.of_dvd_left (Subgroup.card_subgroup_dvd_card f.range)
  rw [Nat.card_congr e.toEquiv]
  exact hrange

/-- Inclusion of a nonnegative lower ramification group into inertia `G₀`. -/
noncomputable def lowerRamificationToInertia (i : ℕ) :
    lowerRamificationGroup F K (i : ℤ) →* lowerRamificationGroup F K 0 :=
  Subgroup.inclusion (lowerRamificationGroup_antitone F K (by omega))

@[simp]
theorem lowerRamificationToInertia_coe (i : ℕ)
    (σ : lowerRamificationGroup F K (i : ℤ)) :
    ((lowerRamificationToInertia (F := F) (K := K) i σ :
      lowerRamificationGroup F K 0) : Gal(K/F)) = (σ : Gal(K/F)) :=
  rfl

/-- The manuscript's additive coefficient map on the positive lower group `G_i`. -/
noncomputable def wildInertiaCoefficientHom (i : ℕ) (hi : 1 ≤ i) :
    lowerRamificationGroup F K (i : ℤ) →*
      Multiplicative (ResidueField K) where
  toFun σ := Multiplicative.ofAdd
    (lowerRamificationResidueDisplacement F K σ
      (inertiaUniformizer (F := F) (K := K) : K)
      (inertiaUniformizer_isUniformizer (F := F) (K := K)))
  map_one' := by
    let π : K := inertiaUniformizer (F := F) (K := K)
    let hπ := inertiaUniformizer_isUniformizer (F := F) (K := K)
    let d := lowerRamificationNormalizedDisplacement F K
      (1 : lowerRamificationGroup F K (i : ℤ)) π hπ
    have hzero : (0 : K) ∈ lattice K 0 := (lattice K 0).zero_mem
    change reduce K (d : K) d.prop = 0
    calc
      reduce K (d : K) d.prop = reduce K 0 hzero := by
        apply reduce_eq_of_eq (K := K)
        dsimp only [d]
        rw [coe_lowerRamificationNormalizedDisplacement]
        simp
      _ = 0 := rfl
  map_mul' σ τ := by
    let π : K := inertiaUniformizer (F := F) (K := K)
    let hπ := inertiaUniformizer_isUniformizer (F := F) (K := K)
    let σ0 := lowerRamificationToInertia (F := F) (K := K) i σ
    let rσ := lowerRamificationTameRatio F K σ0 π hπ
    let dσ := lowerRamificationNormalizedDisplacement F K σ π hπ
    let dτ := lowerRamificationNormalizedDisplacement F K τ π hπ
    let dστ := lowerRamificationNormalizedDisplacement F K (σ * τ) π hπ
    have hdτg : (σ : Gal(K/F)) (dτ : K) ∈ lattice K 0 :=
      galois_mem_lattice_zero (F := F) (K := K) (σ : Gal(K/F)) dτ.prop
    have hrpow : (rσ : K) ^ (i + 1) ∈ lattice K 0 := by
      induction i + 1 with
      | zero => simp
      | succ n hn =>
          simpa [pow_succ] using mul_mem_lattice K hn rσ.prop
    have hprod : (σ : Gal(K/F)) (dτ : K) * (rσ : K) ^ (i + 1) ∈
        lattice K 0 := by
      simpa using mul_mem_lattice K hdτg hrpow
    have hsum : (σ : Gal(K/F)) (dτ : K) * (rσ : K) ^ (i + 1) +
        (dσ : K) ∈ lattice K 0 := (lattice K 0).add_mem hprod dσ.prop
    have hfield : (dστ : K) =
        (σ : Gal(K/F)) (dτ : K) * (rσ : K) ^ (i + 1) + (dσ : K) := by
      dsimp only [dστ, dτ, rσ, σ0, dσ]
      simp only [coe_lowerRamificationNormalizedDisplacement,
        coe_lowerRamificationTameRatio, Subgroup.coe_mul, AlgEquiv.mul_apply,
        map_sub, map_div₀]
      have hσ0coe : (σ0 : Gal(K/F)) = (σ : Gal(K/F)) := rfl
      rw [hσ0coe]
      rw [show ((i : ℤ) + 1) = ((i + 1 : ℕ) : ℤ) by omega,
        zpow_natCast, map_pow, div_pow]
      rw [div_mul_div_cancel₀
        (pow_ne_zero _ ((map_ne_zero (σ : Gal(K/F))).2 hπ.ne_zero))]
      ring
    have hσone : tameInertiaHom (F := F) (K := K) σ0 = 1 := by
      apply (tameInertiaHom_eq_one_iff (F := F) (K := K) σ0).2
      exact lowerRamificationGroup_antitone F K (by exact_mod_cast hi) σ.prop
    have hrone : reduce K (rσ : K) rσ.prop = 1 := by
      have h := congrArg (fun u : (ResidueField K)ˣ => (u : ResidueField K)) hσone
      change reduce K (rσ : K) rσ.prop = 1 at h
      exact h
    have hdτred : reduce K ((σ : Gal(K/F)) (dτ : K)) hdτg =
        reduce K (dτ : K) dτ.prop := by
      simpa [σ0, lowerRamificationToInertia] using
        (reduce_galois_of_mem_lowerRamificationGroup_zero
          (F := F) (K := K) σ0 dτ.prop)
    change reduce K (dστ : K) dστ.prop =
      reduce K (dσ : K) dσ.prop + reduce K (dτ : K) dτ.prop
    calc
      reduce K (dστ : K) dστ.prop =
          reduce K
            ((σ : Gal(K/F)) (dτ : K) * (rσ : K) ^ (i + 1) + (dσ : K))
            hsum := reduce_eq_of_eq (K := K) dστ.prop hsum hfield
      _ = reduce K
            ((σ : Gal(K/F)) (dτ : K) * (rσ : K) ^ (i + 1)) hprod +
          reduce K (dσ : K) dσ.prop := reduce_add (K := K) hprod dσ.prop
      _ = (reduce K ((σ : Gal(K/F)) (dτ : K)) hdτg) *
            reduce K ((rσ : K) ^ (i + 1)) hrpow +
          reduce K (dσ : K) dσ.prop := by
        rw [reduce_mul (K := K) hdτg hrpow]
      _ = reduce K (dτ : K) dτ.prop *
            (reduce K (rσ : K) rσ.prop) ^ (i + 1) +
          reduce K (dσ : K) dσ.prop := by
        rw [hdτred,
          reduce_pow (K := K) rσ.prop (i + 1) hrpow]
      _ = reduce K (dσ : K) dσ.prop + reduce K (dτ : K) dτ.prop := by
        rw [hrone]
        simp [add_comm]

private theorem wildResidue_eq_zero_iff_congruent
    (i : ℕ) (_hi : 1 ≤ i)
    (σ : lowerRamificationGroup F K (i : ℤ)) :
    lowerRamificationResidueDisplacement F K σ
        (inertiaUniformizer (F := F) (K := K) : K)
        (inertiaUniformizer_isUniformizer (F := F) (K := K)) = 0 ↔
      CongruentAtDepth ((i : ℤ) + 2)
        ((σ : Gal(K/F)) (inertiaUniformizer (F := F) (K := K) : K))
        (inertiaUniformizer (F := F) (K := K) : K) := by
  let π := inertiaUniformizer (F := F) (K := K)
  let hπ := inertiaUniformizer_isUniformizer (F := F) (K := K)
  let z := lowerRamificationNormalizedDisplacement F K σ (π : K) hπ
  change residueMap K
      ⟨(z : K), (mem_lattice_zero_iff K).1 z.prop⟩ = 0 ↔ _
  rw [residueMap_eq_zero_iff]
  change (((σ : Gal(K/F)) (π : K) - (π : K)) /
      (π : K) ^ ((i : ℤ) + 1)) ∈ lattice K 1 ↔ _
  rw [div_mem_lattice_iff K ((π : K) ^ ((i : ℤ) + 1))
    ((σ : Gal(K/F)) (π : K) - (π : K)) ((i : ℤ) + 1) 1
    (ord_uniformizer_zpow K hπ ((i : ℤ) + 1))]
  exact (congruentAtDepth_iff_sub_mem_lattice K ((i : ℤ) + 2)
    ((σ : Gal(K/F)) (π : K)) (π : K)).symm

/-- The additive coefficient vanishes exactly on the next lower ramification group. -/
@[simp]
theorem wildInertiaCoefficientHom_eq_one_iff
    (i : ℕ) (hi : 1 ≤ i)
    (σ : lowerRamificationGroup F K (i : ℤ)) :
    wildInertiaCoefficientHom (F := F) (K := K) i hi σ = 1 ↔
      (σ : Gal(K/F)) ∈ lowerRamificationGroup F K ((i + 1 : ℕ) : ℤ) := by
  let σ0 := lowerRamificationToInertia (F := F) (K := K) i σ
  have hcriterion := mem_lowerRamificationGroup_iff_inertiaUniformizer
    (F := F) (K := K) σ0 ((i : ℤ) + 1)
  have hcoefficient := wildResidue_eq_zero_iff_congruent
    (F := F) (K := K) i hi σ
  change lowerRamificationResidueDisplacement F K σ
      (inertiaUniformizer (F := F) (K := K) : K)
      (inertiaUniformizer_isUniformizer (F := F) (K := K)) = 0 ↔ _
  rw [show ((i + 1 : ℕ) : ℤ) = (i : ℤ) + 1 by omega]
  exact hcoefficient.trans hcriterion.symm

/-- Exact kernel of every positive-depth additive coefficient map. -/
theorem wildInertiaCoefficientHom_ker (i : ℕ) (hi : 1 ≤ i) :
    (wildInertiaCoefficientHom (F := F) (K := K) i hi).ker =
      lowerRamificationGroupInside F K
        (show (i : ℤ) ≤ ((i + 1 : ℕ) : ℤ) by omega) := by
  ext σ
  rw [MonoidHom.mem_ker, wildInertiaCoefficientHom_eq_one_iff,
    mem_lowerRamificationGroupInside]

/-- Every element of a positive lower group has its residue-characteristic power in the next
lower group. -/
private theorem pow_residueCharacteristic_mem_next
    (i : ℕ) (hi : 1 ≤ i)
    (σ : lowerRamificationGroup F K (i : ℤ)) :
    (((σ : Gal(K/F)) ^ residueCharacteristic K) : Gal(K/F)) ∈
      lowerRamificationGroup F K ((i + 1 : ℕ) : ℤ) := by
  let c := wildInertiaCoefficientHom (F := F) (K := K) i hi
  have hcpow : (c σ) ^ residueCharacteristic K = 1 := by
    change residueCharacteristic K • Multiplicative.toAdd (c σ) = 0
    rw [nsmul_eq_mul, CharP.cast_eq_zero, zero_mul]
  have hmap : c (σ ^ residueCharacteristic K) = 1 := by
    rw [map_pow, hcpow]
  exact (wildInertiaCoefficientHom_eq_one_iff
    (F := F) (K := K) i hi (σ ^ residueCharacteristic K)).1 hmap

/-- Wild inertia `G₁` is a `p`-group for the actual residue characteristic. -/
theorem wildInertia_isPGroup :
    IsPGroup (residueCharacteristic F) (lowerRamificationGroup F K 1) := by
  rw [← residueCharacteristic_extension_eq F K]
  let p := residueCharacteristic K
  intro σ
  obtain ⟨N, hNnonneg, hNbot⟩ :=
    lowerRamificationGroup_eventually_bot F K
  let n : ℕ := N.toNat
  refine ⟨n, ?_⟩
  have hlevels : ∀ m : ℕ,
      ((σ : Gal(K/F)) ^ p ^ m) ∈
        lowerRamificationGroup F K ((m + 1 : ℕ) : ℤ) := by
    intro m
    induction m with
    | zero =>
        simp
    | succ m hm =>
        let τ : lowerRamificationGroup F K ((m + 1 : ℕ) : ℤ) :=
          ⟨(σ : Gal(K/F)) ^ p ^ m, hm⟩
        have hnext := pow_residueCharacteristic_mem_next
          (F := F) (K := K) (m + 1) (Nat.succ_le_succ (Nat.zero_le m)) τ
        simpa only [p, τ, pow_succ, pow_mul] using hnext
  have hNle : N ≤ ((n + 1 : ℕ) : ℤ) := by
    dsimp only [n]
    omega
  have hbot : lowerRamificationGroup F K ((n + 1 : ℕ) : ℤ) = ⊥ :=
    hNbot _ hNle
  apply Subtype.ext
  have hmem : ((σ : Gal(K/F)) ^ p ^ n) ∈ (⊥ : Subgroup Gal(K/F)) := by
    rw [← hbot]
    exact hlevels n
  simpa using hmem

end

end LanglandsSecondMainLemma.Ramification
