import LanglandsFirstMainLemma.FiniteField.ArtinSchreier
import LanglandsFirstMainLemma.FiniteField.FrobeniusTrace
import LanglandsFirstMainLemma.FiniteField.QuadraticPhase
import LanglandsFirstMainLemma.LocalField.Extension
import LanglandsFirstMainLemma.LocalField.Lattices
import LanglandsFirstMainLemma.LocalField.MonogenicUniformizer
import LanglandsFirstMainLemma.LocalField.Valuation
import LanglandsSecondMainLemma.Local.Newton
import Mathlib.Algebra.Polynomial.Eval.Irreducible
import Mathlib.FieldTheory.PrimitiveElement
import Mathlib.NumberTheory.Padics.RingHoms
import Mathlib.RingTheory.DiscreteValuationRing.TFAE
import Mathlib.RingTheory.Localization.Finiteness

/-!
# Unramified coefficient fields

This file formalizes the construction in `epsilon_SML.tex`, lines 8230--8250.
Given a finite extension `k / ZMod p`, choose a primitive element, lift its
monic minimal polynomial to `ℤ_[p]`, and take the corresponding `AdjoinRoot`.

The resulting coefficient ring is finite free over `ℤ_[p]`, is a complete
discrete valuation ring with maximal ideal generated by `p`, and has residue
field `k`. Its fraction field is a finite extension of `ℚ_[p]` of the same
degree as the lifted polynomial. No choice of multiplicative representatives
is made here; that belongs to the subsequent Teichmüller-lift construction.
-/

namespace LanglandsSecondMainLemma.Gauss

open Polynomial

noncomputable section

private theorem mem_smul_top_iff_repr
    {A M : Type*} [CommRing A] [AddCommGroup M] [Module A M]
    {ι : Type*} [Fintype ι] (b : Module.Basis ι A M)
    (I : Ideal A) (x : M) :
    x ∈ I • (⊤ : Submodule A M) ↔ ∀ i, b.repr x i ∈ I := by
  constructor
  · intro hx i
    refine Submodule.smul_induction_on hx ?_ ?_
    · intro r hr y hy
      simpa using I.mul_mem_right (b.repr y i) hr
    · intro x y hx hy
      simpa using I.add_mem hx hy
  · intro hx
    rw [← b.sum_repr x]
    exact Submodule.sum_mem _ fun i _ =>
      Submodule.smul_mem_smul (hx i) (Submodule.mem_top)

private theorem isAdicComplete_of_finite_basis
    {A M : Type*} [CommRing A] [AddCommGroup M] [Module A M]
    {ι : Type*} [Fintype ι] (b : Module.Basis ι A M)
    (I : Ideal A) [IsAdicComplete I A] : IsAdicComplete I M where
  haus' x hx := by
    apply b.repr.injective
    ext i
    have : b.repr x i = 0 := by
      apply IsHausdorff.haus (I := I) (IsAdicComplete.toIsHausdorff)
      intro n
      rw [SModEq.zero, smul_eq_mul, Ideal.mul_top]
      have hxn := hx n
      rw [SModEq.zero] at hxn
      exact (mem_smul_top_iff_repr b (I ^ n) x).mp hxn i
    simpa using this
  prec' f hf := by
    have hcoord (i : ι) :
        ∃ L : A, ∀ n, b.repr (f n) i ≡ L [SMOD (I ^ n • ⊤ : Submodule A A)] := by
      apply IsPrecomplete.prec (I := I) (M := A) (IsAdicComplete.toIsPrecomplete)
      intro m n hmn
      rw [SModEq.sub_mem]
      have hmn' := hf hmn
      rw [SModEq.sub_mem] at hmn'
      have hmem := (mem_smul_top_iff_repr b (I ^ m) (f m - f n)).mp hmn' i
      simpa [smul_eq_mul, Ideal.mul_top] using hmem
    choose L hL using hcoord
    refine ⟨b.equivFun.symm L, fun n => ?_⟩
    rw [SModEq.sub_mem]
    apply (mem_smul_top_iff_repr b (I ^ n) _).mpr
    intro i
    have hi := hL i n
    rw [SModEq.sub_mem, smul_eq_mul, Ideal.mul_top] at hi
    simpa [Module.Basis.equivFun] using hi

private theorem adjoinRoot_local
    {A κ : Type*} [CommRing A] [IsDomain A] [IsLocalRing A]
    [UniqueFactorizationMonoid A[X]]
    [Field κ]
    (q : A →+* κ) (hq : Function.Surjective q)
    (hker : RingHom.ker q = IsLocalRing.maximalIdeal A)
    (g : κ[X]) (hg : Irreducible g)
    (P : A[X]) (hPmonic : P.Monic) (hPred : P.map q = g) :
    let hp : Prime P := UniqueFactorizationMonoid.irreducible_iff_prime.mp
      (Polynomial.Monic.irreducible_of_irreducible_map q P hPmonic (hPred.symm ▸ hg))
    letI : IsDomain (AdjoinRoot P) := AdjoinRoot.isDomain_of_prime hp
    IsLocalRing (AdjoinRoot P) := by
  dsimp only
  let hp : Prime P := UniqueFactorizationMonoid.irreducible_iff_prime.mp
    (Polynomial.Monic.irreducible_of_irreducible_map q P hPmonic (hPred.symm ▸ hg))
  letI : IsDomain (AdjoinRoot P) := AdjoinRoot.isDomain_of_prime hp
  letI : Fact (Irreducible g) := ⟨hg⟩
  letI : Field (AdjoinRoot g) := AdjoinRoot.instField
  let R := AdjoinRoot P
  letI : Module.Finite A R := hPmonic.finite_adjoinRoot
  let I : Ideal R := (IsLocalRing.maximalIdeal A).map (algebraMap A R)
  have hqquot : IsField (R ⧸ I) := by
    let e₀ := AdjoinRoot.quotEquivQuotMap P (IsLocalRing.maximalIdeal A)
    let e₀' : (R ⧸ I) ≃+*
        AdjoinRoot (P.map (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A))) :=
      e₀.toRingEquiv
    let eA : A ⧸ IsLocalRing.maximalIdeal A ≃+* κ :=
      (Ideal.quotEquivOfEq hker.symm).trans
        (RingHom.quotientKerEquivOfSurjective hq)
    let e₁ : AdjoinRoot (P.map (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A))) ≃+*
        AdjoinRoot g := AdjoinRoot.mapRingEquiv eA
          (P.map (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A))) g (by
          apply Associated.of_eq
          rw [← hPred, Polynomial.map_map]
          congr 2)
    let e : (R ⧸ I) ≃+* AdjoinRoot g := e₀'.trans e₁
    exact e.toMulEquiv.isField (Field.toIsField (AdjoinRoot g))
  have hImax : I.IsMaximal :=
    (Ideal.Quotient.maximal_ideal_iff_isField_quotient I).mpr hqquot
  apply IsLocalRing.of_unique_max_ideal
  refine ⟨I, hImax, ?_⟩
  intro J hJ
  haveI : J.IsMaximal := hJ
  have hcomapMax : (J.comap (algebraMap A R)).IsMaximal :=
    Ideal.isMaximal_comap_of_isIntegral_of_isMaximal J
  have hcomap : J.comap (algebraMap A R) = IsLocalRing.maximalIdeal A :=
    IsLocalRing.eq_maximalIdeal hcomapMax
  exact (hImax.eq_of_le hJ.ne_top (by
    change (IsLocalRing.maximalIdeal A).map (algebraMap A R) ≤ J
    rw [Ideal.map_le_iff_le_comap, hcomap])).symm

private theorem adjoinRoot_maximalIdeal_eq
    {A κ : Type*} [CommRing A] [IsDomain A] [IsLocalRing A]
    [UniqueFactorizationMonoid A[X]] [Field κ]
    (q : A →+* κ) (hq : Function.Surjective q)
    (hker : RingHom.ker q = IsLocalRing.maximalIdeal A)
    (g : κ[X]) (hg : Irreducible g)
    (P : A[X]) (hPmonic : P.Monic) (hPred : P.map q = g) :
    let hp : Prime P := UniqueFactorizationMonoid.irreducible_iff_prime.mp
      (Polynomial.Monic.irreducible_of_irreducible_map q P hPmonic (hPred.symm ▸ hg))
    letI : IsDomain (AdjoinRoot P) := AdjoinRoot.isDomain_of_prime hp
    letI : IsLocalRing (AdjoinRoot P) :=
      adjoinRoot_local q hq hker g hg P hPmonic hPred
    IsLocalRing.maximalIdeal (AdjoinRoot P) =
      (IsLocalRing.maximalIdeal A).map (algebraMap A (AdjoinRoot P)) := by
  dsimp only
  let hp : Prime P := UniqueFactorizationMonoid.irreducible_iff_prime.mp
    (Polynomial.Monic.irreducible_of_irreducible_map q P hPmonic (hPred.symm ▸ hg))
  letI : IsDomain (AdjoinRoot P) := AdjoinRoot.isDomain_of_prime hp
  letI : IsLocalRing (AdjoinRoot P) :=
    adjoinRoot_local q hq hker g hg P hPmonic hPred
  letI : Fact (Irreducible g) := ⟨hg⟩
  letI : Field (AdjoinRoot g) := AdjoinRoot.instField
  let R := AdjoinRoot P
  let I : Ideal R := (IsLocalRing.maximalIdeal A).map (algebraMap A R)
  have hqquot : IsField (R ⧸ I) := by
    let e₀ := AdjoinRoot.quotEquivQuotMap P (IsLocalRing.maximalIdeal A)
    let e₀' : (R ⧸ I) ≃+*
        AdjoinRoot (P.map (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A))) :=
      e₀.toRingEquiv
    let eA : A ⧸ IsLocalRing.maximalIdeal A ≃+* κ :=
      (Ideal.quotEquivOfEq hker.symm).trans
        (RingHom.quotientKerEquivOfSurjective hq)
    let e₁ : AdjoinRoot (P.map (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A))) ≃+*
        AdjoinRoot g := AdjoinRoot.mapRingEquiv eA
          (P.map (Ideal.Quotient.mk (IsLocalRing.maximalIdeal A))) g (by
          apply Associated.of_eq
          rw [← hPred, Polynomial.map_map]
          congr 2)
    let e : (R ⧸ I) ≃+* AdjoinRoot g := e₀'.trans e₁
    exact e.toMulEquiv.isField (Field.toIsField (AdjoinRoot g))
  exact (IsLocalRing.eq_maximalIdeal
    ((Ideal.Quotient.maximal_ideal_iff_isField_quotient I).mpr hqquot)).symm

private theorem padicAdjoinRoot_dvr
    (p : ℕ) [Fact p.Prime]
    (P : ℤ_[p][X]) (hPmonic : P.Monic) (hp : Prime P)
    (hlocal : letI : IsDomain (AdjoinRoot P) := AdjoinRoot.isDomain_of_prime hp
      IsLocalRing (AdjoinRoot P))
    (hmax : letI : IsDomain (AdjoinRoot P) := AdjoinRoot.isDomain_of_prime hp
      letI : IsLocalRing (AdjoinRoot P) := hlocal
      IsLocalRing.maximalIdeal (AdjoinRoot P) =
        (IsLocalRing.maximalIdeal ℤ_[p]).map (algebraMap ℤ_[p] (AdjoinRoot P))) :
    letI : IsDomain (AdjoinRoot P) := AdjoinRoot.isDomain_of_prime hp
    letI : IsLocalRing (AdjoinRoot P) := hlocal
    IsDiscreteValuationRing (AdjoinRoot P) := by
  letI : IsDomain (AdjoinRoot P) := AdjoinRoot.isDomain_of_prime hp
  letI : IsLocalRing (AdjoinRoot P) := hlocal
  letI : Module.Free ℤ_[p] (AdjoinRoot P) := hPmonic.free_adjoinRoot
  have hinj : Function.Injective (algebraMap ℤ_[p] (AdjoinRoot P)) :=
    FaithfulSMul.algebraMap_injective ℤ_[p] (AdjoinRoot P)
  have hp0 : (p : ℤ_[p]) ≠ 0 := by
    exact_mod_cast (Fact.out : p.Prime).ne_zero
  have hpi : algebraMap ℤ_[p] (AdjoinRoot P) (p : ℤ_[p]) ≠ 0 := by
    intro h
    apply hp0
    apply hinj
    simpa using h
  have hmaxne : IsLocalRing.maximalIdeal (AdjoinRoot P) ≠ ⊥ := by
    rw [hmax, PadicInt.maximalIdeal_eq_span_p, Ideal.map_span, Set.image_singleton]
    simpa [Ideal.span_singleton_eq_bot] using hpi
  have hnotfield : ¬ IsField (AdjoinRoot P) :=
    IsLocalRing.isField_iff_maximalIdeal_eq.not.mpr hmaxne
  have hprincipal : (IsLocalRing.maximalIdeal (AdjoinRoot P)).IsPrincipal := by
    rw [hmax, PadicInt.maximalIdeal_eq_span_p, Ideal.map_span, Set.image_singleton]
    infer_instance
  exact ((IsDiscreteValuationRing.TFAE (AdjoinRoot P) hnotfield).out 4 0).mp hprincipal

private theorem padicAdjoinRoot_complete
    (p : ℕ) [Fact p.Prime]
    (P : ℤ_[p][X]) (hPmonic : P.Monic) (hp : Prime P)
    (hlocal : letI : IsDomain (AdjoinRoot P) := AdjoinRoot.isDomain_of_prime hp
      IsLocalRing (AdjoinRoot P))
    (hmax : letI : IsDomain (AdjoinRoot P) := AdjoinRoot.isDomain_of_prime hp
      letI : IsLocalRing (AdjoinRoot P) := hlocal
      IsLocalRing.maximalIdeal (AdjoinRoot P) =
        (IsLocalRing.maximalIdeal ℤ_[p]).map (algebraMap ℤ_[p] (AdjoinRoot P))) :
    letI : IsDomain (AdjoinRoot P) := AdjoinRoot.isDomain_of_prime hp
    letI : IsLocalRing (AdjoinRoot P) := hlocal
    IsAdicComplete (IsLocalRing.maximalIdeal (AdjoinRoot P)) (AdjoinRoot P) := by
  letI : IsDomain (AdjoinRoot P) := AdjoinRoot.isDomain_of_prime hp
  letI : IsLocalRing (AdjoinRoot P) := hlocal
  have hbase : IsAdicComplete (IsLocalRing.maximalIdeal ℤ_[p]) (AdjoinRoot P) :=
    isAdicComplete_of_finite_basis (AdjoinRoot.powerBasis' hPmonic).basis
      (IsLocalRing.maximalIdeal ℤ_[p])
  rw [hmax]
  exact (IsAdicComplete.map_algebraMap_iff
    (IsLocalRing.maximalIdeal ℤ_[p]) (AdjoinRoot P)).mpr hbase

private noncomputable def padicAdjoinRoot_residueEquiv
    (p : ℕ) [Fact p.Prime]
    (k : Type*) [Field k] [Algebra (ZMod p) k]
    (pb : PowerBasis (ZMod p) k)
    (P : ℤ_[p][X])
    (hPred : P.map PadicInt.toZMod = minpoly (ZMod p) pb.gen)
    (hp : Prime P)
    (hlocal : letI : IsDomain (AdjoinRoot P) := AdjoinRoot.isDomain_of_prime hp
      IsLocalRing (AdjoinRoot P))
    (hmax : letI : IsDomain (AdjoinRoot P) := AdjoinRoot.isDomain_of_prime hp
      letI : IsLocalRing (AdjoinRoot P) := hlocal
      IsLocalRing.maximalIdeal (AdjoinRoot P) =
        (IsLocalRing.maximalIdeal ℤ_[p]).map (algebraMap ℤ_[p] (AdjoinRoot P))) :
    letI : IsDomain (AdjoinRoot P) := AdjoinRoot.isDomain_of_prime hp
    letI : IsLocalRing (AdjoinRoot P) := hlocal
    IsLocalRing.ResidueField (AdjoinRoot P) ≃+* k := by
  letI : IsDomain (AdjoinRoot P) := AdjoinRoot.isDomain_of_prime hp
  letI : IsLocalRing (AdjoinRoot P) := hlocal
  let g := minpoly (ZMod p) pb.gen
  let e₀ : IsLocalRing.ResidueField (AdjoinRoot P) ≃+*
      (AdjoinRoot P ⧸ (IsLocalRing.maximalIdeal ℤ_[p]).map
        (algebraMap ℤ_[p] (AdjoinRoot P))) := Ideal.quotEquivOfEq hmax
  let e₁ := (AdjoinRoot.quotEquivQuotMap P (IsLocalRing.maximalIdeal ℤ_[p])).toRingEquiv
  let eA : ℤ_[p] ⧸ IsLocalRing.maximalIdeal ℤ_[p] ≃+* ZMod p :=
    (Ideal.quotEquivOfEq PadicInt.ker_toZMod.symm).trans
      (RingHom.quotientKerEquivOfSurjective
        (ZMod.ringHom_surjective PadicInt.toZMod))
  let e₂ : AdjoinRoot (P.map (Ideal.Quotient.mk (IsLocalRing.maximalIdeal ℤ_[p]))) ≃+*
      AdjoinRoot g := AdjoinRoot.mapRingEquiv eA _ _ (by
        apply Associated.of_eq
        change Polynomial.map eA
          (P.map (Ideal.Quotient.mk (IsLocalRing.maximalIdeal ℤ_[p]))) =
            minpoly (ZMod p) pb.gen
        rw [← hPred, Polynomial.map_map]
        congr 2)
  let e₃ : AdjoinRoot g ≃+* k :=
    (AdjoinRoot.equiv' g pb (by simp [g]) (by simp [g])).toRingEquiv
  exact e₀.trans (e₁.trans (e₂.trans e₃))

private noncomputable abbrev padicFractionAlgebra
    (p : ℕ) [Fact p.Prime]
    (P : ℤ_[p][X]) (hPmonic : P.Monic) (hp : Prime P) :
    letI : IsDomain (AdjoinRoot P) := AdjoinRoot.isDomain_of_prime hp
    Algebra ℚ_[p] (FractionRing (AdjoinRoot P)) := by
  letI : IsDomain (AdjoinRoot P) := AdjoinRoot.isDomain_of_prime hp
  letI : Module.Free ℤ_[p] (AdjoinRoot P) := hPmonic.free_adjoinRoot
  let g : ℤ_[p] →+* FractionRing (AdjoinRoot P) :=
    (algebraMap (AdjoinRoot P) (FractionRing (AdjoinRoot P))).comp
      (algebraMap ℤ_[p] (AdjoinRoot P))
  have hg : Function.Injective g :=
    (IsFractionRing.injective (AdjoinRoot P) (FractionRing (AdjoinRoot P))).comp
      (FaithfulSMul.algebraMap_injective ℤ_[p] (AdjoinRoot P))
  exact (IsFractionRing.lift hg).toAlgebra

private theorem padicFraction_finite
    (p : ℕ) [Fact p.Prime]
    (P : ℤ_[p][X]) (hPmonic : P.Monic) (hp : Prime P) :
    letI : IsDomain (AdjoinRoot P) := AdjoinRoot.isDomain_of_prime hp
    letI : Algebra ℚ_[p] (FractionRing (AdjoinRoot P)) :=
      padicFractionAlgebra p P hPmonic hp
    Module.Finite ℚ_[p] (FractionRing (AdjoinRoot P)) ∧
      Module.finrank ℚ_[p] (FractionRing (AdjoinRoot P)) =
        Module.finrank ℤ_[p] (AdjoinRoot P) := by
  letI : IsDomain (AdjoinRoot P) := AdjoinRoot.isDomain_of_prime hp
  letI : Module.Free ℤ_[p] (AdjoinRoot P) := hPmonic.free_adjoinRoot
  letI : Module.Finite ℤ_[p] (AdjoinRoot P) := hPmonic.finite_adjoinRoot
  let K := FractionRing (AdjoinRoot P)
  let g : ℤ_[p] →+* K :=
    (algebraMap (AdjoinRoot P) K).comp (algebraMap ℤ_[p] (AdjoinRoot P))
  have hg : Function.Injective g :=
    (IsFractionRing.injective (AdjoinRoot P) K).comp
      (FaithfulSMul.algebraMap_injective ℤ_[p] (AdjoinRoot P))
  letI : Algebra ℚ_[p] K := padicFractionAlgebra p P hPmonic hp
  letI : IsScalarTower ℤ_[p] ℚ_[p] K := IsScalarTower.of_algebraMap_eq (fun x ↦ by
    change g x = IsFractionRing.lift hg ((algebraMap ℤ_[p] ℚ_[p]) x)
    exact (IsFractionRing.lift_algebraMap hg x).symm)
  have hfinrank : Module.finrank ℚ_[p] K = Module.finrank ℤ_[p] (AdjoinRoot P) :=
    Algebra.IsAlgebraic.finrank_of_isFractionRing ℤ_[p] ℚ_[p]
      (AdjoinRoot P) K
  have hpos : 0 < Module.finrank ℚ_[p] K := by
    rw [hfinrank]
    exact Module.finrank_pos
  exact ⟨FiniteDimensional.of_finrank_pos hpos, hfinrank⟩

/-- The data and proved arithmetic properties of the coefficient-ring
construction attached to a finite field `k / ZMod p`. -/
structure UnramifiedCoefficientLift
    (p : ℕ) [Fact p.Prime]
    (k : Type*) [Field k] [Algebra (ZMod p) k] where
  residuePowerBasis : PowerBasis (ZMod p) k
  polynomial : ℤ_[p][X]
  polynomial_monic : polynomial.Monic
  polynomial_reduction : polynomial.map PadicInt.toZMod =
    minpoly (ZMod p) residuePowerBasis.gen
  polynomial_natDegree : polynomial.natDegree =
    (minpoly (ZMod p) residuePowerBasis.gen).natDegree
  polynomial_prime : Prime polynomial
  coefficientFree : Module.Free ℤ_[p] (AdjoinRoot polynomial)
  coefficientFinite : Module.Finite ℤ_[p] (AdjoinRoot polynomial)
  localRing :
    letI : IsDomain (AdjoinRoot polynomial) :=
      AdjoinRoot.isDomain_of_prime polynomial_prime
    IsLocalRing (AdjoinRoot polynomial)
  maximalIdeal_eq :
    letI : IsDomain (AdjoinRoot polynomial) :=
      AdjoinRoot.isDomain_of_prime polynomial_prime
    letI : IsLocalRing (AdjoinRoot polynomial) := localRing
    IsLocalRing.maximalIdeal (AdjoinRoot polynomial) =
      (IsLocalRing.maximalIdeal ℤ_[p]).map
        (algebraMap ℤ_[p] (AdjoinRoot polynomial))
  discreteValuationRing :
    letI : IsDomain (AdjoinRoot polynomial) :=
      AdjoinRoot.isDomain_of_prime polynomial_prime
    letI : IsLocalRing (AdjoinRoot polynomial) := localRing
    IsDiscreteValuationRing (AdjoinRoot polynomial)
  complete :
    letI : IsDomain (AdjoinRoot polynomial) :=
      AdjoinRoot.isDomain_of_prime polynomial_prime
    letI : IsLocalRing (AdjoinRoot polynomial) := localRing
    IsAdicComplete (IsLocalRing.maximalIdeal (AdjoinRoot polynomial))
      (AdjoinRoot polynomial)
  residueEquiv :
    letI : IsDomain (AdjoinRoot polynomial) :=
      AdjoinRoot.isDomain_of_prime polynomial_prime
    letI : IsLocalRing (AdjoinRoot polynomial) := localRing
    IsLocalRing.ResidueField (AdjoinRoot polynomial) ≃+* k
  fractionAlgebra :
    letI : IsDomain (AdjoinRoot polynomial) :=
      AdjoinRoot.isDomain_of_prime polynomial_prime
    Algebra ℚ_[p] (FractionRing (AdjoinRoot polynomial))
  fractionFinite :
    letI : IsDomain (AdjoinRoot polynomial) :=
      AdjoinRoot.isDomain_of_prime polynomial_prime
    letI : Algebra ℚ_[p] (FractionRing (AdjoinRoot polynomial)) := fractionAlgebra
    Module.Finite ℚ_[p] (FractionRing (AdjoinRoot polynomial))
  fractionFinrank_eq :
    letI : IsDomain (AdjoinRoot polynomial) :=
      AdjoinRoot.isDomain_of_prime polynomial_prime
    letI : Algebra ℚ_[p] (FractionRing (AdjoinRoot polynomial)) := fractionAlgebra
    Module.finrank ℚ_[p] (FractionRing (AdjoinRoot polynomial)) =
      polynomial.natDegree
  fractionFinrank_eq_residue :
    letI : IsDomain (AdjoinRoot polynomial) :=
      AdjoinRoot.isDomain_of_prime polynomial_prime
    letI : Algebra ℚ_[p] (FractionRing (AdjoinRoot polynomial)) := fractionAlgebra
    Module.finrank ℚ_[p] (FractionRing (AdjoinRoot polynomial)) =
      Module.finrank (ZMod p) k

/-- Every finite field extension of `ZMod p` occurs as the residue field of a
finite free complete DVR over `ℤ_[p]`; its fraction field is finite over
`ℚ_[p]` and has degree equal to the degree of the lifted polynomial. -/
theorem unramifiedCoefficientLift_exists
    (p : ℕ) [Fact p.Prime]
    (k : Type*) [Field k] [Finite k] [Algebra (ZMod p) k] :
    Nonempty (UnramifiedCoefficientLift p k) := by
  let pb := Field.powerBasisOfFiniteOfSeparable (ZMod p) k
  let g := minpoly (ZMod p) pb.gen
  have hgen : IsIntegral (ZMod p) pb.gen := pb.isIntegral_gen
  have hgmonic : g.Monic := minpoly.monic hgen
  have hgirreducible : Irreducible g := minpoly.irreducible hgen
  obtain ⟨P, hPred, hPdegree, hPmonic⟩ :=
    Polynomial.lifts_and_natDegree_eq_and_monic
      (Polynomial.mem_lifts_of_surjective
        (ZMod.ringHom_surjective PadicInt.toZMod) g) hgmonic
  have hPirreducible : Irreducible P :=
    Polynomial.Monic.irreducible_of_irreducible_map PadicInt.toZMod P hPmonic
      (hPred.symm ▸ hgirreducible)
  let hPprime : Prime P :=
    UniqueFactorizationMonoid.irreducible_iff_prime.mp hPirreducible
  let hlocal :
      letI : IsDomain (AdjoinRoot P) := AdjoinRoot.isDomain_of_prime hPprime
      IsLocalRing (AdjoinRoot P) :=
    adjoinRoot_local PadicInt.toZMod
      (ZMod.ringHom_surjective PadicInt.toZMod) PadicInt.ker_toZMod
      g hgirreducible P hPmonic hPred
  let hmax :
      letI : IsDomain (AdjoinRoot P) := AdjoinRoot.isDomain_of_prime hPprime
      letI : IsLocalRing (AdjoinRoot P) := hlocal
      IsLocalRing.maximalIdeal (AdjoinRoot P) =
        (IsLocalRing.maximalIdeal ℤ_[p]).map (algebraMap ℤ_[p] (AdjoinRoot P)) :=
    adjoinRoot_maximalIdeal_eq PadicInt.toZMod
      (ZMod.ringHom_surjective PadicInt.toZMod) PadicInt.ker_toZMod
      g hgirreducible P hPmonic hPred
  let hdvr := padicAdjoinRoot_dvr p P hPmonic hPprime hlocal hmax
  let hcomplete := padicAdjoinRoot_complete p P hPmonic hPprime hlocal hmax
  let eresidue := padicAdjoinRoot_residueEquiv p k pb P hPred
    hPprime hlocal hmax
  let falgebra := padicFractionAlgebra p P hPmonic hPprime
  have hf := padicFraction_finite p P hPmonic hPprime
  refine ⟨{
    residuePowerBasis := pb
    polynomial := P
    polynomial_monic := hPmonic
    polynomial_reduction := hPred
    polynomial_natDegree := hPdegree
    polynomial_prime := hPprime
    coefficientFree := hPmonic.free_adjoinRoot
    coefficientFinite := hPmonic.finite_adjoinRoot
    localRing := hlocal
    maximalIdeal_eq := hmax
    discreteValuationRing := hdvr
    complete := hcomplete
    residueEquiv := eresidue
    fractionAlgebra := falgebra
    fractionFinite := hf.1
    fractionFinrank_eq := ?_
    fractionFinrank_eq_residue := ?_
  }⟩
  · calc
    Module.finrank ℚ_[p] (FractionRing (AdjoinRoot P)) =
        Module.finrank ℤ_[p] (AdjoinRoot P) := hf.2
    _ = (AdjoinRoot.powerBasis' hPmonic).dim :=
      (AdjoinRoot.powerBasis' hPmonic).finrank
    _ = P.natDegree := AdjoinRoot.powerBasis'_dim hPmonic
  · calc
    Module.finrank ℚ_[p] (FractionRing (AdjoinRoot P)) = P.natDegree := by
      calc
        _ = Module.finrank ℤ_[p] (AdjoinRoot P) := hf.2
        _ = (AdjoinRoot.powerBasis' hPmonic).dim :=
          (AdjoinRoot.powerBasis' hPmonic).finrank
        _ = P.natDegree := AdjoinRoot.powerBasis'_dim hPmonic
    _ = g.natDegree := hPdegree
    _ = pb.dim := pb.natDegree_minpoly
    _ = Module.finrank (ZMod p) k := pb.finrank.symm

end

end LanglandsSecondMainLemma.Gauss
