import LanglandsFirstMainLemma.LocalField.FiniteQuotients
import LanglandsSecondMainLemma.Basic.Characters
import Mathlib.Algebra.Category.Grp.Injective
import Mathlib.FieldTheory.IsAlgClosed.Basic
import Mathlib.GroupTheory.Finiteness

/-!
# Local / Character Extension

Blueprint: blueprint/tasks/Local/CharacterExtension.md
Paper: C:character-extension

This file proves the paper's character-extension lemma by descending through a positive unit
filtration, extending on the resulting finitely generated abelian quotient, and pulling back.
It also records the several-subgroup reduction and preservation of arbitrary prescribed values.

The characters throughout are bundled group homomorphisms with codomain `ℂˣ`.
-/

namespace LanglandsSecondMainLemma.Local

noncomputable section

open CategoryTheory
open LanglandsFirstMainLemma

/-- Every nonzero complex number has an `n`th root which is still nonzero. -/
@[implicit_reducible]
private noncomputable def complexUnitsRootableByNat : RootableBy ℂˣ ℕ :=
  rootableByOfPowLeftSurj ℂˣ ℕ (by
    intro n hn u
    obtain ⟨z, hz⟩ := IsAlgClosed.exists_pow_nat_eq (u : ℂ) (Nat.pos_of_ne_zero hn)
    have hz0 : z ≠ 0 := by
      intro hzero
      rw [hzero, zero_pow hn] at hz
      exact u.ne_zero hz.symm
    refine ⟨Units.mk0 z hz0, ?_⟩
    apply Units.ext
    exact hz)

/-- Multiplicative rootability is additive divisibility after applying the type tag. -/
@[implicit_reducible]
private noncomputable def additiveDivisibleByIntOfRootable
    (A : Type*) [CommGroup A] [RootableBy A ℤ] :
    DivisibleBy (Additive A) ℤ where
  div a n := Additive.ofMul (RootableBy.root a.toMul n)
  div_zero a := Additive.toMul.injective (RootableBy.root_zero a.toMul)
  div_cancel a hn := Additive.toMul.injective (RootableBy.root_cancel a.toMul hn)

/-- A homomorphism from a subgroup of an abelian group to `ℂˣ` extends to the whole
group.  This is the algebraic step used only after passing to the discrete quotient. -/
private theorem exists_monoidHom_extension {G : Type u} [CommGroup G] [Group.FG G]
    (H : Subgroup G) (chi : H →* ℂˣ) :
    ∃ extension : G →* ℂˣ, extension.comp H.subtype = chi := by
  letI : RootableBy ℂˣ ℕ := complexUnitsRootableByNat
  letI : RootableBy ℂˣ ℤ := Group.rootableByIntOfRootableByNat ℂˣ
  letI : RootableBy (ULift.{u} ℂˣ) ℤ := inferInstance
  letI : DivisibleBy (Additive (ULift.{u} ℂˣ)) ℤ :=
    additiveDivisibleByIntOfRootable (ULift.{u} ℂˣ)
  let liftedChi : H →* ULift.{u} ℂˣ :=
    MulEquiv.ulift.symm.toMonoidHom.comp chi
  let inclusion : Additive H →+ Additive G := H.subtype.toAdditive
  let prescribed : Additive H →+ Additive (ULift.{u} ℂˣ) := liftedChi.toAdditive
  let inclusionCat : AddCommGrpCat.of (Additive H) ⟶
      AddCommGrpCat.of (Additive G) := AddCommGrpCat.ofHom inclusion
  let prescribedCat : AddCommGrpCat.of (Additive H) ⟶
      AddCommGrpCat.of (Additive (ULift.{u} ℂˣ)) := AddCommGrpCat.ofHom prescribed
  letI : Mono inclusionCat :=
    (AddCommGrpCat.mono_iff_injective inclusionCat).2 (by
      intro x y hxy
      exact Additive.toMul.injective (Subtype.ext (Additive.ofMul.injective hxy)))
  let extendedCat : AddCommGrpCat.of (Additive G) ⟶
      AddCommGrpCat.of (Additive (ULift.{u} ℂˣ)) :=
    Injective.factorThru prescribedCat inclusionCat
  let extension : G →* ℂˣ :=
    MulEquiv.ulift.toMonoidHom.comp extendedCat.hom.toMultiplicative
  refine ⟨extension, ?_⟩
  apply MonoidHom.ext
  intro h
  have hfactor := ConcreteCategory.congr_hom
    (Injective.comp_factorThru prescribedCat inclusionCat)
  exact congrArg ULift.down (hfactor (Additive.ofMul h))

/-- The quotient used in Paper C.2 is finitely generated.  Concretely it is generated by
the class of one uniformizer together with the finite quotient `U⁰/Uᵐ`. -/
private theorem unitFiltrationQuotient_fg
    (E : Type u) [Field E] [ValuativeRel E] [TopologicalSpace E]
    [IsNonarchimedeanLocalField E] (m : ℕ) :
    Group.FG (Eˣ ⧸ unitFiltration E m) := by
  let U : Subgroup Eˣ := unitFiltration E m
  let q : Eˣ →* Eˣ ⧸ U := QuotientGroup.mk' U
  let pi0 : E := Classical.choose (exists_ord_eq E 1)
  have hpi0 : ord E pi0 = (1 : WithTop ℤ) :=
    Classical.choose_spec (exists_ord_eq E 1)
  have hpi0_ne : pi0 ≠ 0 := (ord_ne_top_iff E).1 (by simp [hpi0])
  let pi : Eˣ := Units.mk0 pi0 hpi0_ne
  have hpi : ord E (pi : E) = (1 : WithTop ℤ) := hpi0
  let hm : 0 ≤ m := Nat.zero_le m
  let unitToQuotient : UnitFiltrationQuotient E 0 m hm →* Eˣ ⧸ U :=
    QuotientGroup.lift (unitFiltrationInside E hm)
      (q.comp (unitFiltration E 0).subtype) (by
        intro u hu
        rw [MonoidHom.mem_ker]
        apply (QuotientGroup.eq_one_iff _).2
        exact (mem_unitFiltrationInside E hm u).1 hu)
  let powers : Multiplicative ℤ →* Eˣ ⧸ U :=
    { toFun := fun n ↦ q (pi ^ n.toAdd)
      map_one' := by simp
      map_mul' := by
        intro a b
        simp only [toAdd_mul, zpow_add, map_mul] }
  let assemble : Multiplicative ℤ × UnitFiltrationQuotient E 0 m hm →*
      Eˣ ⧸ U :=
    { toFun := fun x ↦ powers x.1 * unitToQuotient x.2
      map_one' := by
        simp only [Prod.fst_one, Prod.snd_one, map_one]
        exact mul_one (1 : Eˣ ⧸ U)
      map_mul' := by
        intro a b
        simp only [Prod.fst_mul, Prod.snd_mul, map_mul]
        exact mul_mul_mul_comm (powers a.1) (powers b.1)
          (unitToQuotient a.2) (unitToQuotient b.2) }
  letI : Finite (UnitFiltrationQuotient E 0 m hm) :=
    finiteUnitFiltrationQuotient E hm
  letI : Group.FG (Multiplicative ℤ × UnitFiltrationQuotient E 0 m hm) :=
    inferInstance
  change Group.FG (Eˣ ⧸ U)
  apply Group.fg_of_surjective
    (G := Multiplicative ℤ × UnitFiltrationQuotient E 0 m hm)
    (G' := Eˣ ⧸ U) (f := assemble)
  intro y
  induction y using Quotient.inductionOn' with
  | _ x =>
      obtain ⟨n, hn⟩ := WithTop.ne_top_iff_exists.mp
        ((ord_ne_top_iff E).2 (Units.ne_zero x))
      let u : Eˣ := pi ^ (-n) * x
      have huord : ord E (u : E) = 0 := by
        dsimp only [u]
        rw [Units.val_mul, Units.val_zpow_eq_zpow_val, ord_mul,
          ord_zpow, hpi, ← hn]
        cases n with
        | ofNat n => simp
        | negSucc n =>
            rw [Int.neg_negSucc, natCast_zsmul]
            change (n + 1) • ((1 : ℤ) : WithTop ℤ) +
              (Int.negSucc n : WithTop ℤ) = 0
            calc
              (n + 1) • ((1 : ℤ) : WithTop ℤ) + (Int.negSucc n : WithTop ℤ) =
                  (((n + 1) • (1 : ℤ) + Int.negSucc n : ℤ) : WithTop ℤ) := by
                    rw [WithTop.coe_add, WithTop.coe_nsmul]
              _ = ((0 : ℤ) : WithTop ℤ) := by
                exact congrArg (fun z : ℤ ↦ (z : WithTop ℤ)) (by
                  simp [Int.negSucc_eq])
              _ = 0 := rfl
      let u0 : unitFiltration E 0 :=
        ⟨u, (mem_unitFiltration_zero E u).2 huord⟩
      refine ⟨(Multiplicative.ofAdd n, unitFiltrationQuotientMk E hm u0), ?_⟩
      change q (pi ^ n) * q (u : Eˣ) = q x
      rw [← map_mul]
      congr 1
      dsimp only [u]
      rw [← mul_assoc, ← zpow_add]
      simp

/-- An algebraic character which kills an open unit-filtration layer is continuous. -/
private theorem continuous_of_trivialOnUnitFiltration
    (E : Type u) [Field E] [ValuativeRel E] [TopologicalSpace E]
    [IsNonarchimedeanLocalField E] (f : Eˣ →* ℂˣ) (m : ℕ)
    (hf : ∀ u : Eˣ, u ∈ unitFiltration E m → f u = 1) :
    Continuous f := by
  apply continuous_of_continuousAt_one f
  rw [ContinuousAt, map_one]
  rw [Filter.tendsto_def]
  intro V hV
  have hopen : IsOpen (unitFiltration E m : Set Eˣ) :=
    unitFiltration_isOpen E m
  have hone : (1 : Eˣ) ∈ unitFiltration E m :=
    (unitFiltration E m).one_mem
  refine Filter.mem_of_superset (hopen.mem_nhds hone) ?_
  intro u hu
  change f u ∈ V
  rw [hf u hu]
  exact mem_of_mem_nhds hV

/-- **Paper C.2 (`C:character-extension`).**

Let `H ≤ Eˣ` contain a positive unit-filtration layer.  Every group homomorphism
`chi : H →* ℂˣ` whose restriction to that layer is trivial extends to a continuous
quasi-character of `E`.

The hypothesis `htrivial` is an equality of actual group homomorphisms on the restricted
domain `unitFiltration E m`; it is not a pointwise condition on an unrelated function. -/
theorem characterExtension
    (E : Type u) [Field E] [ValuativeRel E] [TopologicalSpace E]
    [IsNonarchimedeanLocalField E]
    (H : Subgroup Eˣ) (m : ℕ) (_hm : 1 ≤ m)
    (hUH : unitFiltration E m ≤ H) (chi : H →* ℂˣ)
    (htrivial : chi.comp (Subgroup.inclusion hUH) = 1) :
    ∃ extension : ContinuousQuasiChar E,
      extension.toMonoidHom.comp H.subtype = chi := by
  let U : Subgroup Eˣ := unitFiltration E m
  let q : Eˣ →* Eˣ ⧸ U := QuotientGroup.mk' U
  let qH : H →* Eˣ ⧸ U := q.comp H.subtype
  have hker : qH.ker ≤ chi.ker := by
    intro h hh
    have hq : q (h : Eˣ) = 1 := by
      exact (MonoidHom.mem_ker.mp hh)
    have hu : (h : Eˣ) ∈ unitFiltration E m := by
      exact (QuotientGroup.eq_one_iff (h : Eˣ)).1 hq
    have hvalue := DFunLike.congr_fun htrivial
      (⟨(h : Eˣ), hu⟩ : unitFiltration E m)
    rw [MonoidHom.mem_ker]
    simp only [MonoidHom.comp_apply, MonoidHom.one_apply] at hvalue
    calc
      chi h = chi ((Subgroup.inclusion hUH)
          (⟨(h : Eˣ), hu⟩ : unitFiltration E m)) := by
        congr 1
      _ = 1 := hvalue
  let chiQuotient : H ⧸ qH.ker →* ℂˣ :=
    QuotientGroup.lift qH.ker chi hker
  let firstIso : H ⧸ qH.ker ≃* qH.range :=
    QuotientGroup.quotientKerEquivRange qH
  let descended : qH.range →* ℂˣ :=
    chiQuotient.comp firstIso.symm.toMonoidHom
  have hdescended : descended.comp qH.rangeRestrict = chi := by
    apply MonoidHom.ext
    intro h
    change chiQuotient (firstIso.symm
      (⟨qH h, ⟨h, rfl⟩⟩ : qH.range)) = chi h
    have hinverse : firstIso.symm (⟨qH h, ⟨h, rfl⟩⟩ : qH.range) =
        QuotientGroup.mk h := by
      apply firstIso.injective
      rw [firstIso.apply_symm_apply]
      rfl
    rw [hinverse]
    rfl
  letI : Group.FG (Eˣ ⧸ U) := by
    change Group.FG (Eˣ ⧸ unitFiltration E m)
    exact unitFiltrationQuotient_fg E m
  obtain ⟨extendedQuotient, hextended⟩ :=
    exists_monoidHom_extension (G := Eˣ ⧸ U) qH.range descended
  let pulledBack : Eˣ →* ℂˣ := extendedQuotient.comp q
  have hpulledBackTrivial :
      ∀ u : Eˣ, u ∈ unitFiltration E m → pulledBack u = 1 := by
    intro u hu
    change extendedQuotient (q u) = 1
    have hqu : q u = 1 := by
      apply (QuotientGroup.eq_one_iff u).2
      exact hu
    rw [hqu, map_one]
  let continuousExtension : ContinuousQuasiChar E :=
    { pulledBack with
      continuous_toFun :=
        continuous_of_trivialOnUnitFiltration E pulledBack m hpulledBackTrivial }
  refine ⟨continuousExtension, ?_⟩
  apply MonoidHom.ext
  intro h
  change extendedQuotient (qH h) = chi h
  calc
    extendedQuotient (qH h) =
        descended (⟨qH h, ⟨h, rfl⟩⟩ : qH.range) :=
      DFunLike.congr_fun hextended ⟨qH h, ⟨h, rfl⟩⟩
    _ = chi h := DFunLike.congr_fun hdescended h

/-- An arbitrary prescribed value in `ℂˣ` is retained whenever the element carrying it
belongs to the original subgroup.  In particular, if `x` is a uniformizer in `H`, no
finite-order or unit-circle condition is imposed on its prescribed value `z`. -/
theorem characterExtension_preserves_prescribedValue
    (E : Type u) [Field E] [ValuativeRel E] [TopologicalSpace E]
    [IsNonarchimedeanLocalField E]
    (H : Subgroup Eˣ) (m : ℕ) (hm : 1 ≤ m)
    (hUH : unitFiltration E m ≤ H) (chi : H →* ℂˣ)
    (htrivial : chi.comp (Subgroup.inclusion hUH) = 1)
    (x : H) (z : ℂˣ) (hx : chi x = z) :
    ∃ extension : ContinuousQuasiChar E,
      extension.toMonoidHom.comp H.subtype = chi ∧ extension (x : Eˣ) = z := by
  obtain ⟨extension, hextension⟩ :=
    characterExtension E H m hm hUH chi htrivial
  refine ⟨extension, hextension, ?_⟩
  have hvalue := DFunLike.congr_fun hextension x
  exact hvalue.trans hx

/-- Several compatible subgroup prescriptions reduce to `characterExtension` once they have
been proved to define a single character on the subgroup they generate.

The homomorphism `generatedCharacter` and the restriction equalities `hprescribed` are explicit
hypotheses.  Thus this theorem neither infers multiplicativity merely from pairwise agreement
nor assumes the desired continuous extension. -/
theorem characterExtension_of_iSup
    {I : Type v}
    (E : Type u) [Field E] [ValuativeRel E] [TopologicalSpace E]
    [IsNonarchimedeanLocalField E]
    (H : I → Subgroup Eˣ) (chi : ∀ i, H i →* ℂˣ)
    (generatedCharacter : ↑(⨆ i, H i) →* ℂˣ)
    (hprescribed : ∀ i,
      generatedCharacter.comp (Subgroup.inclusion (le_iSup H i)) = chi i)
    (m : ℕ) (hm : 1 ≤ m) (hU : unitFiltration E m ≤ ⨆ i, H i)
    (htrivial : generatedCharacter.comp (Subgroup.inclusion hU) = 1) :
    ∃ extension : ContinuousQuasiChar E,
      ∀ i, extension.toMonoidHom.comp (H i).subtype = chi i := by
  obtain ⟨extension, hextension⟩ :=
    characterExtension E (⨆ i, H i) m hm hU generatedCharacter htrivial
  refine ⟨extension, ?_⟩
  intro i
  calc
    extension.toMonoidHom.comp (H i).subtype =
        (extension.toMonoidHom.comp (⨆ i, H i).subtype).comp
          (Subgroup.inclusion (le_iSup H i)) := by rfl
    _ = generatedCharacter.comp (Subgroup.inclusion (le_iSup H i)) := by
      rw [hextension]
    _ = chi i := hprescribed i

end

end LanglandsSecondMainLemma.Local
