import LanglandsFirstMainLemma.LocalField.Extension
import LanglandsFirstMainLemma.LocalField.Lattices
import LanglandsFirstMainLemma.LocalField.MonogenicUniformizer
import LanglandsFirstMainLemma.LocalField.Valuation
import LanglandsFirstMainLemma.Ramification.Different
import LanglandsFirstMainLemma.Ramification.LowerGroups
import LanglandsFirstMainLemma.Ramification.NormFiltration
import LanglandsFirstMainLemma.Ramification.SymmetricBounds
import LanglandsSecondMainLemma.Basic.Fields
import LanglandsSecondMainLemma.Basic.NormTrace
import Mathlib.RingTheory.DedekindDomain.Different
import Mathlib.RingTheory.Discriminant

/-!
# Local / Different

Blueprint: blueprint/tasks/Local/Different.md
Paper: C:different-tower, C:order-discriminant

This file specializes Mathlib's transitivity theorem for the different ideal to the canonical
valuation rings of three named local fields.  It also records the discriminant change under a
full-rank change of integral basis and connects the genuine different ideal with FML's
normalized numerical `differentExponent`.

The final bound is stated for the power order generated by an actual integral field generator.
Its right hand side is the order in the base field of the actual trace discriminant of the
power basis.  Thus neither the ideal divisibility nor the passage to normalized valuations is
replaced by a numerical hypothesis.
-/

namespace LanglandsSecondMainLemma.Local

open LanglandsFirstMainLemma
open Matrix
open scoped Pointwise

noncomputable section

attribute [local instance] FractionRing.liftAlgebra

section AlgebraicAdapters

variable {F K : Type*} [Field F] [Field K] [Algebra F K]

/-- The canonical power basis attached to an integral field generator.  This is the power
basis of the monogenic order whose discriminant occurs in Paper C.5. -/
noncomputable def monogenicPowerBasis
    (x : K) (hint : IsIntegral F x)
    (hx : Algebra.adjoin F ({x} : Set K) = ⊤) : PowerBasis F K :=
  PowerBasis.ofAdjoinEqTop hint hx

@[simp]
theorem monogenicPowerBasis_gen
    (x : K) (hint : IsIntegral F x)
    (hx : Algebra.adjoin F ({x} : Set K) = ⊤) :
    (monogenicPowerBasis x hint hx).gen = x := by
  simp [monogenicPowerBasis]

/-- Discriminants change by the square of the determinant of a full-rank change-of-basis
matrix.  Taking principal ideals gives the order-discriminant formula: the second factor is
the square of the index ideal represented by the inclusion matrix. -/
theorem orderDiscriminantIdeal_eq_mul_indexIdeal_sq
    {A B : Type*} [CommRing A] [CommRing B] [Algebra A B] [IsDomain A]
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (bO : Module.Basis ι A B) (M : Matrix ι ι A) (_hfull : M.det ≠ 0) :
    Ideal.span ({Algebra.discr A
        (bO ᵥ* M.map (algebraMap A B))} : Set A) =
      Ideal.span ({Algebra.discr A bO} : Set A) *
        Ideal.span ({M.det} : Set A) ^ 2 := by
  rw [Algebra.discr_of_matrix_vecMul]
  simp only [pow_two, Ideal.span_singleton_mul_span_singleton]
  congr 1
  ring_nf

/-- In particular, the field-basis discriminant ideal divides the discriminant ideal of every
full-rank order whose inclusion matrix is `M`.  Ideal divisibility is retained explicitly. -/
theorem fieldDiscriminantIdeal_dvd_orderDiscriminantIdeal
    {A B : Type*} [CommRing A] [CommRing B] [Algebra A B] [IsDomain A]
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (bO : Module.Basis ι A B) (M : Matrix ι ι A) (hfull : M.det ≠ 0) :
    Ideal.span ({Algebra.discr A bO} : Set A) ∣
      Ideal.span ({Algebra.discr A
        (bO ᵥ* M.map (algebraMap A B))} : Set A) := by
  refine ⟨Ideal.span ({M.det} : Set A) ^ 2, ?_⟩
  exact orderDiscriminantIdeal_eq_mul_indexIdeal_sq bO M hfull

end AlgebraicAdapters

section LocalDifferent

variable (F K : Type*) [Field F] [Field K]
variable [ValuativeRel F] [TopologicalSpace F] [IsNonarchimedeanLocalField F]
variable [ValuativeRel K] [TopologicalSpace K] [IsNonarchimedeanLocalField K]
variable [Algebra F K] [ValuativeExtension F K]
variable [Module.Free F K] [Module.Finite F K] [IsGalois F K]

/-- The genuine different ideal, embedded in the extension field, is exactly the integral
lattice at FML's normalized different exponent.  This is the bridge between Mathlib's ideal
and the numerical exponent used in the local calculations. -/
theorem coeSubmodule_differentIdeal_eq_lattice
    (piK : ringOfIntegers K)
    (hpiK : (ValuativeRel.valuation K).IsUniformizer (piK : K))
    (hgen : Algebra.adjoin (ringOfIntegers F)
      ({piK} : Set (ringOfIntegers K)) = ⊤) :
    IsLocalization.coeSubmodule K
        (differentIdeal (ringOfIntegers F) (ringOfIntegers K)) =
      lattice K (differentExponent F K : ℤ) := by
  letI : Module.Finite (ringOfIntegers F) (ringOfIntegers K) :=
    ringOfIntegers_moduleFinite F K
  letI : IsIntegralClosure (ringOfIntegers K) (ringOfIntegers F) K :=
    ringOfIntegers_isIntegralClosure F K
  rw [coeSubmodule_differentIdeal (ringOfIntegers F) F]
  rw [← lattice_zero K]
  rw [traceDual_lattice_zero F K piK hpiK hgen]
  rw [lattice_div]
  congr 1
  omega

/-- Paper C.5 in the monogenic local form used later.  For an integral element generating
`K/F`, the normalized different exponent is at most the base-field order of the discriminant
of its actual power basis.  Total ramification is the explicit residue-degree-one hypothesis;
it is used only when `ord_norm` converts the upper derivative order to the base order.

The proof first puts the derivative in Mathlib's genuine different ideal, then uses
`coeSubmodule_differentIdeal_eq_lattice` to obtain the upper normalized inequality, and only
then invokes the power-basis discriminant identity. -/
theorem differentExponent_le_ord_discr_of_generator
    (hres : residueDegree F K = 1)
    (x : ringOfIntegers K)
    (hx : Algebra.adjoin F ({(x : K)} : Set K) = ⊤) :
    ((differentExponent F K : ℤ) : WithTop ℤ) ≤
      ord F (Algebra.discr F
        (monogenicPowerBasis (x : K)
          (Algebra.IsIntegral.isIntegral (x : K)) hx).basis) := by
  letI : Module.Finite (ringOfIntegers F) (ringOfIntegers K) :=
    ringOfIntegers_moduleFinite F K
  letI : Module.Free (ringOfIntegers F) (ringOfIntegers K) :=
    Module.free_of_finite_type_torsion_free'
  letI : IsIntegralClosure (ringOfIntegers K) (ringOfIntegers F) K :=
    ringOfIntegers_isIntegralClosure F K
  obtain ⟨piK, hpiK, hpiGen⟩ := monogenicUniformizer F K hres
  let dx : ringOfIntegers K :=
    Polynomial.aeval x
      (Polynomial.derivative (minpoly (ringOfIntegers F) x))
  have hxIntegral : IsIntegral (ringOfIntegers F) x :=
    IsIntegralClosure.isIntegral (ringOfIntegers F) K x
  have hdxMem : dx ∈
      differentIdeal (ringOfIntegers F) (ringOfIntegers K) := by
    exact aeval_derivative_mem_differentIdeal
      (ringOfIntegers F) F K x hx
  have hdxCoeMem : algebraMap (ringOfIntegers K) K dx ∈
      IsLocalization.coeSubmodule K
        (differentIdeal (ringOfIntegers F) (ringOfIntegers K)) := by
    exact (IsLocalization.mem_coeSubmodule K _).2 ⟨dx, hdxMem, rfl⟩
  rw [coeSubmodule_differentIdeal_eq_lattice F K piK hpiK hpiGen] at hdxCoeMem
  have hderiv : algebraMap (ringOfIntegers K) K dx =
      Polynomial.aeval (x : K)
        (Polynomial.derivative (minpoly F (x : K))) := by
    have hcoe : algebraMap (ringOfIntegers K) K x = (x : K) :=
      congrFun (Algebra.coe_algebraMap_ofSubsemiring (ringOfIntegers K)) x
    rw [← hcoe]
    change algebraMap (ringOfIntegers K) K
        (Polynomial.aeval x
          (Polynomial.derivative (minpoly (ringOfIntegers F) x))) = _
    rw [minpoly.isIntegrallyClosed_eq_field_fractions F K hxIntegral,
      Polynomial.derivative_map, Polynomial.aeval_map_algebraMap,
      Polynomial.aeval_algebraMap_apply]
  let pb : PowerBasis F K :=
    monogenicPowerBasis (x : K)
      (Algebra.IsIntegral.isIntegral (x : K)) hx
  have hpbGen : pb.gen = (x : K) := by
    exact monogenicPowerBasis_gen (x : K)
      (Algebra.IsIntegral.isIntegral (x : K)) hx
  have hdisc := Algebra.discr_powerBasis_eq_norm (pb := pb)
  rw [hpbGen] at hdisc
  rw [hdisc, ord_mul, ord_pow, ord_neg, ord_one, nsmul_zero, zero_add,
    ord_norm, hres, one_nsmul, ← hderiv]
  exact hdxCoeMem

end LocalDifferent

section Tower

variable (F L K : Type*) [Field F] [Field L] [Field K]
variable [ValuativeRel F] [TopologicalSpace F] [IsNonarchimedeanLocalField F]
variable [ValuativeRel L] [TopologicalSpace L] [IsNonarchimedeanLocalField L]
variable [ValuativeRel K] [TopologicalSpace K] [IsNonarchimedeanLocalField K]
variable [Algebra F L] [Algebra L K] [Algebra F K] [IsScalarTower F L K]
variable [ValuativeExtension F L] [ValuativeExtension L K] [ValuativeExtension F K]
variable [Module.Free F L] [Module.Finite F L]
variable [Module.Free L K] [Module.Finite L K]
variable [Module.Free F K] [Module.Finite F K]

/-- Paper C.4 for the canonical valuation rings of a finite separable local tower.  The lower
different is extended along the actual map `ᵊ_L → ᵊ_K`; all three ideal domains remain
visible in the statement. -/
theorem differentIdeal_tower [Algebra.IsSeparable F K] :
    differentIdeal (ringOfIntegers F) (ringOfIntegers K) =
      differentIdeal (ringOfIntegers L) (ringOfIntegers K) *
        (differentIdeal (ringOfIntegers F) (ringOfIntegers L)).map
          (algebraMap (ringOfIntegers L) (ringOfIntegers K)) := by
  letI : Module.Finite (ringOfIntegers F) (ringOfIntegers L) :=
    ringOfIntegers_moduleFinite F L
  letI : Module.Finite (ringOfIntegers L) (ringOfIntegers K) :=
    ringOfIntegers_moduleFinite L K
  letI : Module.Finite (ringOfIntegers F) (ringOfIntegers K) :=
    ringOfIntegers_moduleFinite F K
  letI : IsScalarTower (ringOfIntegers F) (ringOfIntegers L)
      (ringOfIntegers K) := IsScalarTower.of_algebraMap_eq fun x => by
    apply Subtype.ext
    change algebraMap F K (x : F) =
      algebraMap L K (algebraMap F L (x : F))
    rw [IsScalarTower.algebraMap_apply F L K]
  letI : IsIntegralClosure (ringOfIntegers L) (ringOfIntegers F) L :=
    ringOfIntegers_isIntegralClosure F L
  letI : IsIntegralClosure (ringOfIntegers K) (ringOfIntegers L) K :=
    ringOfIntegers_isIntegralClosure L K
  letI : IsIntegralClosure (ringOfIntegers K) (ringOfIntegers F) K :=
    ringOfIntegers_isIntegralClosure F K
  letI : Algebra.IsSeparable
      (FractionRing (ringOfIntegers F))
      (FractionRing (ringOfIntegers K)) := by
    refine Algebra.IsSeparable.of_equiv_equiv
      (FractionRing.algEquiv (ringOfIntegers F) F).symm.toRingEquiv
      (FractionRing.algEquiv (ringOfIntegers K) K).symm.toRingEquiv ?_
    ext x
    exact IsFractionRing.algEquiv_commutes
      (FractionRing.algEquiv (ringOfIntegers F) F).symm
      (FractionRing.algEquiv (ringOfIntegers K) K).symm x
  exact differentIdeal_eq_differentIdeal_mul_differentIdeal
    (ringOfIntegers F) (ringOfIntegers L) (ringOfIntegers K)

private theorem span_singleton_eq_smul_lattice_zero
    (E : Type*) [Field E] [ValuativeRel E] [TopologicalSpace E]
    [IsNonarchimedeanLocalField E] (a : E) :
    (ringOfIntegers E) ∙ a = a • lattice E 0 := by
  rw [lattice_zero, Submodule.one_eq_span]
  rw [← Submodule.span_singleton_mul]
  rw [← Submodule.one_eq_span, mul_one]

omit [Algebra F K] [IsScalarTower F L K] [ValuativeExtension F K]
  [Module.Free L K] [Module.Finite L K] [Module.Free F K] [Module.Finite F K] in
/-- Extending the lower different ideal from `L` to `K` multiplies its normalized lattice
depth by the ramification index.  This is the valuation-normalization step in Paper C.4. -/
private theorem coeSubmodule_map_differentIdeal_eq_lattice
    [IsGalois F L] (hresFL : residueDegree F L = 1) :
    IsLocalization.coeSubmodule K
        ((differentIdeal (ringOfIntegers F) (ringOfIntegers L)).map
          (algebraMap (ringOfIntegers L) (ringOfIntegers K))) =
      lattice K
        ((ramificationIndex L K : ℤ) * (differentExponent F L : ℤ)) := by
  let I : Ideal (ringOfIntegers L) :=
    differentIdeal (ringOfIntegers F) (ringOfIntegers L)
  let a : ringOfIntegers L := Submodule.IsPrincipal.generator I
  have hI : Ideal.span ({a} : Set (ringOfIntegers L)) = I :=
    Ideal.span_singleton_generator I
  obtain ⟨piL, hpiL, hpiGen⟩ := monogenicUniformizer F L hresFL
  have hIL : IsLocalization.coeSubmodule L I =
      lattice L (differentExponent F L : ℤ) := by
    exact coeSubmodule_differentIdeal_eq_lattice F L piL hpiL hpiGen
  have hspanL : (ringOfIntegers L) ∙ algebraMap (ringOfIntegers L) L a =
      lattice L (differentExponent F L : ℤ) := by
    calc
      (ringOfIntegers L) ∙ algebraMap (ringOfIntegers L) L a =
          IsLocalization.coeSubmodule L (Ideal.span ({a} : Set (ringOfIntegers L))) :=
        (IsLocalization.coeSubmodule_span_singleton L a).symm
      _ = IsLocalization.coeSubmodule L I := congrArg _ hI
      _ = lattice L (differentExponent F L : ℤ) := hIL
  have haL : ord L (algebraMap (ringOfIntegers L) L a) =
      (((differentExponent F L : ℕ) : ℤ) : WithTop ℤ) := by
    apply (smul_lattice_zero_eq_iff_ord_eq L _ _).1
    rw [← span_singleton_eq_smul_lattice_zero L]
    exact hspanL
  have hmapCoe : algebraMap (ringOfIntegers K) K
      (algebraMap (ringOfIntegers L) (ringOfIntegers K) a) =
      algebraMap L K (algebraMap (ringOfIntegers L) L a) := by
    rfl
  have haK : ord K (algebraMap (ringOfIntegers K) K
      (algebraMap (ringOfIntegers L) (ringOfIntegers K) a)) =
      (((ramificationIndex L K : ℤ) * (differentExponent F L : ℤ) : ℤ) :
        WithTop ℤ) := by
    rw [hmapCoe, ord_algebraMap, haL]
    rw [← WithTop.coe_nsmul]
    congr 1
  calc
    IsLocalization.coeSubmodule K
          ((differentIdeal (ringOfIntegers F) (ringOfIntegers L)).map
            (algebraMap (ringOfIntegers L) (ringOfIntegers K))) =
        IsLocalization.coeSubmodule K
          ((Ideal.span ({a} : Set (ringOfIntegers L))).map
            (algebraMap (ringOfIntegers L) (ringOfIntegers K))) := by
      rw [hI]
    _ = IsLocalization.coeSubmodule K
          (Ideal.span ({algebraMap (ringOfIntegers L)
            (ringOfIntegers K) a} : Set (ringOfIntegers K))) := by
      rw [Ideal.map_span]
      congr 2
      simp
    _ = (ringOfIntegers K) ∙ algebraMap (ringOfIntegers K) K
          (algebraMap (ringOfIntegers L) (ringOfIntegers K) a) :=
      IsLocalization.coeSubmodule_span_singleton K _
    _ = algebraMap (ringOfIntegers K) K
          (algebraMap (ringOfIntegers L) (ringOfIntegers K) a) • lattice K 0 :=
      span_singleton_eq_smul_lattice_zero K _
    _ = lattice K
          ((ramificationIndex L K : ℤ) * (differentExponent F L : ℤ)) :=
      lattice_smul_zero_of_ord_eq K _ _ haK

/-- Numerical form of Paper C.4.  All different exponents use the normalized valuation of
their upper field, so the lower exponent is multiplied by `e(K/L)`. -/
theorem differentExponent_tower
    [IsGalois F L] [IsGalois L K] [IsGalois F K]
    (hresFL : residueDegree F L = 1)
    (hresLK : residueDegree L K = 1)
    (hresFK : residueDegree F K = 1) :
    differentExponent F K =
      differentExponent L K +
        ramificationIndex L K * differentExponent F L := by
  obtain ⟨piK_L, hpiK_L, hpiLK⟩ := monogenicUniformizer L K hresLK
  obtain ⟨piK_F, hpiK_F, hpiFK⟩ := monogenicUniformizer F K hresFK
  have hDFK : IsLocalization.coeSubmodule K
      (differentIdeal (ringOfIntegers F) (ringOfIntegers K)) =
      lattice K (differentExponent F K : ℤ) :=
    coeSubmodule_differentIdeal_eq_lattice F K piK_F hpiK_F hpiFK
  have hDLK : IsLocalization.coeSubmodule K
      (differentIdeal (ringOfIntegers L) (ringOfIntegers K)) =
      lattice K (differentExponent L K : ℤ) :=
    coeSubmodule_differentIdeal_eq_lattice L K piK_L hpiK_L hpiLK
  have hDFLmap : IsLocalization.coeSubmodule K
      ((differentIdeal (ringOfIntegers F) (ringOfIntegers L)).map
        (algebraMap (ringOfIntegers L) (ringOfIntegers K))) =
      lattice K
        ((ramificationIndex L K : ℤ) * (differentExponent F L : ℤ)) :=
    coeSubmodule_map_differentIdeal_eq_lattice F L K hresFL
  have hcoe := congrArg (IsLocalization.coeSubmodule K)
    (differentIdeal_tower F L K)
  rw [IsLocalization.coeSubmodule_mul, hDFK, hDLK, hDFLmap,
    lattice_mul] at hcoe
  have hz : (differentExponent F K : ℤ) =
      (differentExponent L K : ℤ) +
        (ramificationIndex L K : ℤ) * (differentExponent F L : ℤ) :=
    (lattice_eq_lattice_iff K).1 hcoe
  exact_mod_cast hz

/-- Paper C.4: transitivity of the different for a finite separable local tower.  The
normalized totally ramified form and the C.5 order-discriminant adapters are stated
separately in `differentExponent_tower`, `differentExponent_le_ord_discr_of_generator`,
`orderDiscriminantIdeal_eq_mul_indexIdeal_sq`, and
`fieldDiscriminantIdeal_dvd_orderDiscriminantIdeal`. -/
theorem different [Algebra.IsSeparable F K] :
    differentIdeal (ringOfIntegers F) (ringOfIntegers K) =
      differentIdeal (ringOfIntegers L) (ringOfIntegers K) *
        (differentIdeal (ringOfIntegers F) (ringOfIntegers L)).map
          (algebraMap (ringOfIntegers L) (ringOfIntegers K)) :=
  differentIdeal_tower F L K

end Tower

end

end LanglandsSecondMainLemma.Local
